/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgRoundReport.java
 *
 * Created on 28 juin 2010, 10:52:47
 */
package tourma.views.report;

import freemarker.template.Configuration;
import freemarker.template.DefaultObjectWrapper;
import freemarker.template.Template;
import freemarker.template.TemplateException;
import java.awt.Dimension;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.charset.Charset;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import tourma.MainFrame;
import tourma.data.Criteria;
import tourma.data.Round;
import tourma.data.Tournament;
import tourma.tableModel.MjtAnnexRank;
import tourma.tableModel.MjtRanking;
import tourma.utility.StringConstants;

/**
 *
 * @author Frederic Berger
 */
public final class JdgGlobal extends javax.swing.JDialog {
    private static final long serialVersionUID = 12L;

    private int mRoundNumber;
    private Tournament mTour;
//    private boolean mResult;
    private File mFilename = null;
    private MjtRanking mRanking;
    private HashMap<Criteria, MjtAnnexRank> mAnnexAgainstRankings;
    private HashMap<Criteria, MjtAnnexRank> mAnnexForRankings;
    private boolean mClan;
    private boolean mTeam;

    /**
     * Creates new form jdgRoundReport
     * @param parent
     * @param modal
     * @param roundNumber
     * @param tour
     * @param team
     * @param annexForRankings
     * @param model
     * @param annexAgainstRankings
     * @param clan
     */
    public JdgGlobal(final java.awt.Frame parent, final boolean modal, final int roundNumber, final Tournament tour, final MjtRanking model, final HashMap<Criteria, MjtAnnexRank> annexForRankings, final HashMap<Criteria, MjtAnnexRank> annexAgainstRankings, final boolean clan, final boolean team) {
        super(parent, modal);
        initComponents();
        //_round = round;
        mRoundNumber = roundNumber;
        mTour = tour;

        mClan = clan;
        mTeam = team;

        mRanking = model;
        mAnnexForRankings = annexForRankings;
        mAnnexAgainstRankings = annexAgainstRankings;

        this.setTitle(
                tour.getParams().getTournamentName()
                + " - " + java.util.ResourceBundle.getBundle(StringConstants.CS_LANGUAGE_RESOURCE).getString("Round") + " " + roundNumber);
        try {
            jepHTML.setContentType(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("HTML"));
            mFilename = createReport();
            jepHTML.setPage(mFilename.toURI().toURL());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(parent, e.getLocalizedMessage());
        }
        this.setPreferredSize(new Dimension(800, 600));
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jbtPrint = new javax.swing.JButton();
        jbtExport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepHTML = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Ranking"); // NOI18N

        jbtOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Select.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tourma/languages/language"); // NOI18N
        jbtOK.setText(bundle.getString("OK")); // NOI18N
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        jbtPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Document.png"))); // NOI18N
        jbtPrint.setText(bundle.getString("Print")); // NOI18N
        jbtPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrintActionPerformed(evt);
            }
        });
        jPanel1.add(jbtPrint);

        jbtExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Html.png"))); // NOI18N
        jbtExport.setText(bundle.getString("HTMLExport")); // NOI18N
        jbtExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExportActionPerformed(evt);
            }
        });
        jPanel1.add(jbtExport);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(jepHTML);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtOKActionPerformed

    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrintActionPerformed
        try {
            jepHTML.print();

        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(MainFrame.getMainFrame(), e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jbtPrintActionPerformed

    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExportActionPerformed
        final JFileChooser jfc = new JFileChooser();
        if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            final File export = jfc.getSelectedFile();

            OutputStreamWriter out = null;
            InputStreamReader in = null;
            try {
                in = new InputStreamReader(new FileInputStream(mFilename),Charset.defaultCharset());
                {
                    
                    out = new OutputStreamWriter(new FileOutputStream(export),Charset.defaultCharset());
                    int c= in.read();
                    while (c  != -1) {
                        out.write(c);
                         c= in.read();
                    }
                }

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
            }  finally {
                if (in != null) {
                    try {
                        in.close();
                    } catch (IOException e) {
                        LOG.log(Level.INFO, e.getLocalizedMessage());
                    }
                }

                if (out != null) {
                    try {
                        out.close();
                    } catch (IOException e) {
                       LOG.log(Level.INFO,e.getLocalizedMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_jbtExportActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtExport;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtPrint;
    private javax.swing.JEditorPane jepHTML;
    // End of variables declaration//GEN-END:variables

    private File createReport() {

        File address = null;
        Writer out = null;
        try {
            final Configuration cfg = new Configuration();
            final URI uri = getClass().getResource(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("/TOURMA/VIEWS/REPORT")).toURI();
            if (uri.toString().contains(java.util.ResourceBundle.getBundle("tourma/languages/language").getString(".JAR!"))) {
                /*String tmp = uri.toString();
                 tmp = tmp.substring(10, tmp.indexOf(".jar!") - 4);
                 //tmp=tmp+"";
                 cfg.setDirectoryForTemplateLoading(new File(tmp));*/
                cfg.setClassForTemplateLoading(getClass(), java.util.ResourceBundle.getBundle("tourma/languages/language").getString(""));
            } else {
                cfg.setDirectoryForTemplateLoading(new File(uri));
            }
            cfg.setObjectWrapper(new DefaultObjectWrapper());
            final Template temp = cfg.getTemplate(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("GLOBAL.HTML"));

            final ArrayList<Round> rounds;
            rounds = new ArrayList<>();
            for (int i = 0; i < mTour.getRoundsCount() && i < mRoundNumber; i++) {
                rounds.add(mTour.getRound(i));
            }

            final Map root = new HashMap();
            root.put(
                    java.util.ResourceBundle.getBundle("tourma/languages/language").getString("NOM"),
                    mTour.getParams().getTournamentName()
                    + " - " + java.util.ResourceBundle.getBundle(StringConstants.CS_LANGUAGE_RESOURCE).getString("Round") + " " + mRoundNumber);
            String name;
            if (mClan) {
                name = java.util.ResourceBundle.getBundle("tourma/languages/language").getString(" PAR CLAN");
            } else {
                if (mTeam) {
                    name = java.util.ResourceBundle.getBundle("tourma/languages/language").getString(" PAR &EACUTE;QUIPE");
                } else {
                    name = java.util.ResourceBundle.getBundle("tourma/languages/language").getString(" PAR COACH");
                }
            }

            root.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("TITLE"), name);

            final ArrayList titles = new ArrayList();
            for (int i = 0; i < mRanking.getColumnCount(); i++) {
                titles.add(mRanking.getColumnName(i));
            }
            root.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("TITLES"), titles);

            final ArrayList lines = new ArrayList();
            for (int i = 0; i < mRanking.getRowCount(); i++) {
                final HashMap line = new HashMap();
                final ArrayList cols = new ArrayList();
                for (int j = 0; j < mRanking.getColumnCount(); j++) {
                    cols.add(mRanking.getValueAt(i, j));
                }
                line.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("COLS"), cols);
                lines.add(line);
            }
            root.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("LINES"), lines);

            root.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("TITREMOREFOR"), java.util.ResourceBundle.getBundle("tourma/languages/language").getString("LE PLUS R&EACUTE;ALIS&EACUTE;"));
            root.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("TITRELESSFOR"), java.util.ResourceBundle.getBundle("tourma/languages/language").getString("LE MOINS R&EACUTE;ALIS&EACUTE;"));
            root.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("TITREMOREAGAINST"), java.util.ResourceBundle.getBundle("tourma/languages/language").getString("LE PLUS SUBI"));
            root.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("TITRELESSAGAINST"), java.util.ResourceBundle.getBundle("tourma/languages/language").getString("LE MOINS SUBI"));

            final ArrayList criterias = new ArrayList();
            for (int i = 0; i < mTour.getParams().getCriteriaCount(); i++) {
                final HashMap criteria = new HashMap();
                final Criteria c = mTour.getParams().getCriteria(i);
                criteria.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("NAME"), c.getName());

                final MjtAnnexRank annexFor = mAnnexForRankings.get(c);
                final MjtAnnexRank annexAgainst = mAnnexAgainstRankings.get(c);
                criteria.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("MOREFOR"), annexFor.getValueAt(0, 1));
                criteria.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("LESSFOR"), annexFor.getValueAt(annexFor.getRowCount() - 1, 1));
                criteria.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("MOREAGAINST"), annexAgainst.getValueAt(0, 1));
                criteria.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("LESSAGAINST"), annexAgainst.getValueAt(annexAgainst.getRowCount() - 1, 1));

                criterias.add(criteria);
            }
            root.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("CRITERIAS"), criterias);

            final SimpleDateFormat format = new SimpleDateFormat(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("EEEEEEE DD MMMMMMMMMMM YYYY"), Locale.getDefault());
            final SimpleDateFormat formatShort = new SimpleDateFormat(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("DD/MM/YYYY"), Locale.getDefault());
            root.put(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("DATEGENERATION"), formatShort.format(new Date()));
            address = File.createTempFile(
                    java.util.ResourceBundle.getBundle("tourma/languages/language").getString("RESULT") + " " + format.format(new Date()), ".tmp");
            address.deleteOnExit();
            out = new OutputStreamWriter(new FileOutputStream(address),Charset.defaultCharset());
            temp.process(root, out);
            out.flush();

        } catch (IOException | TemplateException | URISyntaxException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } finally {
            if (out != null) {
                try {
                    out.close();
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
                }

            }
        }

        return address;
    }
    private static final Logger LOG = Logger.getLogger(JdgGlobal.class.getName());
/*     private void writeObject(java.io.ObjectOutputStream stream) throws java.io.IOException {
        throw new java.io.NotSerializableException(getClass().getName());
    }

    private void readObject(java.io.ObjectInputStream stream) throws java.io.IOException, ClassNotFoundException {
        throw new java.io.NotSerializableException(getClass().getName());
    }*/
}
