/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgRoundReport.java
 *
 * Created on 28 juin 2010, 10:52:47
 */
package tourma.views.report;

import tourma.*;
import tourma.data.Round;
import tourma.data.Tournament;
import freemarker.template.Configuration;
import freemarker.template.DefaultObjectWrapper;
import freemarker.template.Template;
import freemarker.template.TemplateException;

import java.awt.Dimension;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Frederic Berger
 */
public class jdgRanking extends javax.swing.JDialog {

    public static final int RANKING_GENERAL = 0;
    public static final int RANKING_SCORER = 1;
    public static final int RANKING_DESTROYER = 2;
    public static final int RANKING_FOULER = 3;
    public static final int RANKING_SCORED = 4;
    public static final int RANKING_DESTROYED = 5;
    public static final int RANKING_FOULED = 6;
    Round _round;
    int _roundNumber;
    Tournament _tour;
    boolean _result;
    int _rankType;

    /** Creates new form jdgRoundReport */
    public jdgRanking(java.awt.Frame parent, boolean modal, Round round, int roundNumber, Tournament tour, int RankType) {
        super(parent, modal);
        initComponents();
        _round = round;
        _roundNumber = roundNumber;
        _tour = tour;
        _rankType = RankType;

        this.setTitle(tour.getParams()._tournament_name + " - Ronde " + roundNumber);
        try {
            jepHTML.setContentType("html");
            File f = CreateReport();
            jepHTML.setPage(f.toURI().toURL());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(parent, e.getLocalizedMessage());
        }
        this.setPreferredSize(new Dimension(800, 600));
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jbtPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepHTML = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        jbtPrint.setText("Imprimer");
        jbtPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrintActionPerformed(evt);
            }
        });
        jPanel1.add(jbtPrint);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(jepHTML);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtOKActionPerformed

    private void jbtPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrintActionPerformed
        try {
            jepHTML.print();

        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(MainFrame.getMainFrame(), e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jbtPrintActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtPrint;
    private javax.swing.JEditorPane jepHTML;
    // End of variables declaration//GEN-END:variables

    private File CreateReport() {
        File address = null;

        try {
            Configuration cfg = new Configuration();
            URI uri = getClass().getResource("/tourma/template").toURI();
            if (uri.toString().contains(".jar!")) {
                /*String tmp = uri.toString();
                tmp = tmp.substring(10, tmp.indexOf(".jar!") - 4);
                //tmp=tmp+"";
                cfg.setDirectoryForTemplateLoading(new File(tmp));*/
                cfg.setClassForTemplateLoading(getClass(),"template");
            } else {
                cfg.setDirectoryForTemplateLoading(new File(uri));
            }
            cfg.setObjectWrapper(new DefaultObjectWrapper());
            Template temp = cfg.getTemplate("rank.html");

            TableModel model;
            Vector<Round> rounds = new Vector();
            for (int i = 0; i < _tour.getRounds().size() && i < _roundNumber; i++) {
                rounds.add(_tour.getRounds().get(i));
            }

            Map root = new HashMap();
            root.put("nom", _tour.getParams()._tournament_name + " - Classement Ronde " + _roundNumber);
            switch (_rankType) {
                case RANKING_GENERAL:
                    root.put("title", "Classement général");
                    model = new mjtRanking(rounds, _tour.getParams()._ranking1, _tour.getParams()._ranking2, _tour.getParams()._ranking3, _tour.getParams()._ranking4, _tour.getParams()._ranking5, _tour.getCoachs());
                    break;
                case RANKING_SCORER:
                    root.put("title", "Meilleur Marqueur");
                    model = new mjtAnnexRank(rounds, mjtAnnexRank.C_MOST_TD_POS, _tour.getCoachs(), true);
                    break;
                case RANKING_DESTROYER:
                    root.put("title", "Meilleur Destructeur");
                    model = new mjtAnnexRank(rounds, mjtAnnexRank.C_MOST_SOR_POS, _tour.getCoachs(), true);
                    break;
                case RANKING_FOULER:
                    root.put("title", "Meilleur Crampon");
                    model = new mjtAnnexRank(rounds, mjtAnnexRank.C_MOST_FOUL_POS, _tour.getCoachs(), true);
                    break;
                case RANKING_SCORED:
                    root.put("title", "Pire Passoire");
                    model = new mjtAnnexRank(rounds, mjtAnnexRank.C_MOST_TD_NEG, _tour.getCoachs(), true);
                    break;
                case RANKING_DESTROYED:
                    root.put("title", "Pire Punching Ball");
                    model = new mjtAnnexRank(rounds, mjtAnnexRank.C_MOST_SOR_NEG, _tour.getCoachs(), true);
                    break;
                case RANKING_FOULED:
                    root.put("title", "Pire Paillasson");
                    model = new mjtAnnexRank(rounds, mjtAnnexRank.C_MOST_FOUL_NEG, _tour.getCoachs(), true);
                    break;
                default:
                    root.put("title", "Classement général");
                    model = new mjtRanking(rounds, _tour.getParams()._ranking1, _tour.getParams()._ranking2, _tour.getParams()._ranking3, _tour.getParams()._ranking4, _tour.getParams()._ranking5, _tour.getCoachs());
            }

            Vector rankLines = new Vector();
            Vector titles = new Vector();
            for (int i = 0; i < model.getColumnCount(); i++) {
                titles.add(model.getColumnName(i));
            }
            root.put("titles", titles);

            for (int i = 0; i < model.getRowCount(); i++) {
                HashMap line = new HashMap();
                Vector l = new Vector();
                for (int j = 0; j < model.getColumnCount(); j++) {
                    l.add(model.getValueAt(i, j));
                }
                line.put("cols", l);
                rankLines.add(line);
            }

            root.put("lines", rankLines);

            SimpleDateFormat format = new SimpleDateFormat("EEEEEEE dd MMMMMMMMMMM yyyy");
            SimpleDateFormat formatShort = new SimpleDateFormat("dd/MM/yyyy");
            root.put("dateGeneration", formatShort.format(new Date()));
            address = File.createTempFile("result" + format.format(new Date()), ".tmp");
            address.deleteOnExit();
            Writer out = new FileWriter(address);
            temp.process(root, out);
            out.flush();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (TemplateException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (URISyntaxException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        }
        return address;
    }
}
