/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tourma.views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.DisplayMode;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.ScrollPane;
import java.awt.Scrollbar;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.ScrollPaneConstants;
import tourma.data.Clan;
import tourma.data.Coach;
import tourma.data.CoachMatch;
import tourma.data.Competitor;
import tourma.data.Criteria;
import tourma.data.IWithNameAndPicture;
import tourma.data.Match;
import tourma.data.Round;
import tourma.data.Team;
import tourma.data.TeamMatch;
import tourma.data.Tournament;
import tourma.utils.ImageTreatment;
import tourma.views.GraphicalMatch;

/**
 *
 * @author WFMJ7631
 */
public abstract class JFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form FullScreen
     */
    public JFullScreen() {
        super();
        initComponents();
        this.getGraphicsConfiguration().getDevice().setFullScreenWindow(this);
        GridBagLayout gbl = new GridBagLayout();
        jpnContent.setLayout(gbl);
    }

    protected JLabel getLabelForObject(IWithNameAndPicture object, int height, int width, Font f, Color bkg) {

        JLabel l = new JLabel();
        if (object.getPicture() != null) {
            l.setIcon(ImageTreatment.resize(new ImageIcon(object.getPicture()), height, height));
        } else {
            if (!(object instanceof Coach)) {
                l.setIcon(new ImageIcon(new BufferedImage(height, height, BufferedImage.TYPE_4BYTE_ABGR)));
            }
        }

        //l.setPreferredSize(new Dimension(width, height));
        l.setFont(f);
        l.setOpaque(true);
        l.setBackground(bkg);

        String text = object.getName();
        l.setText(text);
        return l;
    }

    protected GridBagConstraints getGridbBagConstraints(int x, int y, int height, int width) {
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = x;
        gbc.gridy = y;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.gridheight = height;
        gbc.gridwidth = width;
        return gbc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jscrp = new javax.swing.JScrollPane();
        jpnContent = new javax.swing.JPanel();
        jpnNorth = new javax.swing.JPanel();

        setAlwaysOnTop(true);
        setName("FullScreen Tourma"); // NOI18N
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpnContentLayout = new javax.swing.GroupLayout(jpnContent);
        jpnContent.setLayout(jpnContentLayout);
        jpnContentLayout.setHorizontalGroup(
            jpnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        jpnContentLayout.setVerticalGroup(
            jpnContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jscrp.setViewportView(jpnContent);

        getContentPane().add(jscrp, java.awt.BorderLayout.CENTER);

        jpnNorth.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(jpnNorth, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean animationStarted = false;
    Animation animation;

    public class Animation extends Thread {

        public void run() {
            long computedTime = getHeight() / 100;
            //int blockIncrement = jscrp.getVerticalScrollBar().getBlockIncrement();

            //System.out.println("Screen Height: " + getHeight() + " ScrollBar size: " + (jscrp.getVerticalScrollBar().getMaximum() - jscrp.getVerticalScrollBar().getMinimum()) + " Computed Time: " + computedTime);
            int lastValue = 0;
            while (animationStarted) {
                int value = jscrp.getVerticalScrollBar().getValue();
                value = value + 1;
                if (value <= lastValue) {
                    value = 0;
                    try {
                        sleep(10000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(JFullScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    jscrp.getVerticalScrollBar().setValue(jscrp.getVerticalScrollBar().getMinimum());
                } else {
                    jscrp.getVerticalScrollBar().setValue(value);
                }

                try {
                    sleep(computedTime);
                } catch (InterruptedException ex) {
                    Logger.getLogger(JFullScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
                //System.out.println("Current value: " + value + " last Value: " + lastValue);
                lastValue = value;
            }
        }
    }

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
        if (evt.getKeyCode() == KeyEvent.VK_S) {
            if (animationStarted) {
                jscrp.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
                jscrp.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
                animationStarted = false;
                if (animation.isAlive()) {
                    try {
                        animation.join();
                    } catch (InterruptedException ex) {
                        Logger.getLogger(JFullScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                jscrp.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
                jscrp.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
                animationStarted = true;
                animation = new Animation();
                animation.start();
            }

        }
    }//GEN-LAST:event_formKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel jpnContent;
    protected javax.swing.JPanel jpnNorth;
    protected javax.swing.JScrollPane jscrp;
    // End of variables declaration//GEN-END:variables
}
