/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * jdgCoach.java
 *
 * Created on 10 mai 2010, 19:37:53
 */
package tourma;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.SpinnerNumberModel;
import tourma.data.Coach;
import tourma.data.Competitor;
import tourma.data.Cup;
import tourma.data.Round;
import tourma.data.Team;
import tourma.data.TeamMatch;
import tourma.data.Tournament;
import tourma.languages.Translate;
import tourma.tableModel.MjtManualMatchs;
import tourma.tableModel.MjtPairs;
import tourma.views.report.JdgRound;

/**
 *
 * @author Frederic Berger
 */
@SuppressWarnings("serial")
public class JdgManualCupDraw extends javax.swing.JDialog {

    ArrayList<Competitor> mComps;
    ArrayList<Competitor> mTargetComps;

    /**
     * Creates new form jdgCoach
     *
     * @param parent
     * @param modal
     *
     */
    public JdgManualCupDraw(final java.awt.Frame parent, final boolean modal, ArrayList<Competitor> competitors) {
        super(parent, modal);
        initComponents();

        final GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        final GraphicsDevice gs = ge.getDefaultScreenDevice();
        final DisplayMode dmode = gs.getDisplayMode();

        final int screenWidth = dmode.getWidth();
        final int screenHeight = dmode.getHeight();

        this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);

        mComps = competitors;
        mTargetComps = new ArrayList<>();

        
        
        update();
    }

    private void update() {

        jbtAdd.setEnabled(mComps.size() > 0);

        final ArrayList<String> compsNames = new ArrayList<>();
        for (Competitor mPlayersTmp1 : mComps) {
            if (mPlayersTmp1 == null) {
                System.err.println("Null competitor detected");
            } else {

                String name = mPlayersTmp1.getDecoratedName();
                compsNames.add(name);
            }
        }
        
        ActionListener al=jcbLeft.getActionListeners()[0];
        jcbLeft.removeActionListener(al);
        ActionListener ar=jcbRight.getActionListeners()[0];
        jcbRight.removeActionListener(ar);
        
        jcbLeft.removeAllItems();
        jcbRight.removeAllItems();

        for (int i = 0; i < compsNames.size(); i++) {
            if (i == 0) {
                jcbLeft.addItem(compsNames.get(i));
            } else {
                if (i == 1) {
                    jcbRight.addItem(compsNames.get(i));
                } else {
                    jcbLeft.addItem(compsNames.get(i));
                    jcbRight.addItem(compsNames.get(i));
                }
            }

        }

        jcbLeft.addActionListener(al);
        jcbRight.addActionListener(ar);
        jtbMatches.setModel(new MjtManualMatchs(this.mTargetComps));

        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    @SuppressFBWarnings(
            value = "UI_INHERITANCE_UNSAFE_GETRESOURCE",
            justification = "GeneratedCode")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCupType = new javax.swing.ButtonGroup();
        bgInitialDraw = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jcbLeft = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jcbRight = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jbtAdd = new javax.swing.JButton();
        jpnMain = new javax.swing.JPanel();
        jsp = new javax.swing.JScrollPane();
        jtbMatches = new javax.swing.JTable();
        jpnDel = new javax.swing.JPanel();
        jbtDel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jbtOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Select.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tourma/languages/language"); // NOI18N
        jbtOK.setText(bundle.getString("OK")); // NOI18N
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel2.add(jbtOK);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jcbLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbLeftActionPerformed(evt);
            }
        });
        jPanel5.add(jcbLeft, new java.awt.GridBagConstraints());

        jLabel1.setText(" vs ");
        jPanel5.add(jLabel1, new java.awt.GridBagConstraints());

        jcbRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRightActionPerformed(evt);
            }
        });
        jPanel5.add(jcbRight, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jbtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Add.png"))); // NOI18N
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        jPanel6.add(jbtAdd);

        jPanel1.add(jPanel6, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jpnMain.setLayout(new java.awt.BorderLayout());

        jsp.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("MATCHS"))); // NOI18N

        jtbMatches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbMatches.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jsp.setViewportView(jtbMatches);

        jpnMain.add(jsp, java.awt.BorderLayout.CENTER);

        jbtDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Close.png"))); // NOI18N
        jbtDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDelActionPerformed(evt);
            }
        });
        jpnDel.add(jbtDel);

        jpnMain.add(jpnDel, java.awt.BorderLayout.EAST);

        getContentPane().add(jpnMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        for (Competitor c : mTargetComps) {
            mComps.add(c);
        }

        this.setVisible(false);

    }//GEN-LAST:event_jbtOKActionPerformed

    private void jcbLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbLeftActionPerformed
        // Change order in the list. Set the selected competitor at position 0

        int index = jcbLeft.getSelectedIndex();
        if (index >= 0) {
            Competitor tmp = mComps.get(0);
            if (index > 0) {
                tmp = mComps.get(index + 1);
            }
            mComps.remove(tmp);
            mComps.add(0, tmp);
        }
        
        jcbLeft.removeAllItems();
        
        update();
                
    }//GEN-LAST:event_jcbLeftActionPerformed

    private void jcbRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRightActionPerformed
        int index = jcbRight.getSelectedIndex();
        if (index >= 0) {
            Competitor tmp = mComps.get(1);
            if (index > 0) {
                tmp = mComps.get(index + 1);
            }
            mComps.remove(tmp);
            mComps.add(1, tmp);
        }
        
        jcbRight.removeAllItems();
        update();
    }//GEN-LAST:event_jcbRightActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        Competitor c1 = mComps.get(0);
        Competitor c2 = mComps.get(1);

        mComps.remove(c1);
        mComps.remove(c2);

        mTargetComps.add(c1);
        mTargetComps.add(c2);

        update();

    }//GEN-LAST:event_jbtAddActionPerformed

    private void jbtDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDelActionPerformed

        int index = jtbMatches.getSelectedRow();

        if (index >= 0) {
            Competitor c1 = mTargetComps.get(2 * index);
            Competitor c2 = mTargetComps.get(2 * index + 1);

            mComps.add(c1);
            mComps.add(c2);

            mTargetComps.remove(c1);
            mTargetComps.remove(c2);
        }
        update();
    }//GEN-LAST:event_jbtDelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCupType;
    private javax.swing.ButtonGroup bgInitialDraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtDel;
    private javax.swing.JButton jbtOK;
    private javax.swing.JComboBox<String> jcbLeft;
    private javax.swing.JComboBox<String> jcbRight;
    private javax.swing.JPanel jpnDel;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JScrollPane jsp;
    private javax.swing.JTable jtbMatches;
    // End of variables declaration//GEN-END:variables

}
