/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgAbout.java
 *
 * Created on 27 mai 2009, 11:08:24
 */

package tourma.views.system;

import tourma.*;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author root.106572700130
 */
public class jdgAbout extends javax.swing.JDialog {

    /** Creates new form jdgAbout */
    public jdgAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        this.setSize(580, 350);

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        jlbNom.setText("Nom: "+Version.getSingleton().getProperty("long_name"));
        jlbDate.setText("Date: "+Version.getSingleton().getProperty("date"));
        jlbVersion.setText("Version: "+Version.getSingleton().getProperty("version"));

        jlbFreeMarker.setText(Version.getSingleton().getProperty("freemarker"));
        jlbFreeMarkerC.setText(Version.getSingleton().getProperty("freemarker_copyright"));
        jlbJCommon.setText(Version.getSingleton().getProperty("jcommon"));
        jlbJCommonC.setText(Version.getSingleton().getProperty("jcommon_copyright"));
        jlbJDom.setText(Version.getSingleton().getProperty("jdom"));
        jlbJDomC.setText(Version.getSingleton().getProperty("jdom_copyright"));
        jlbSubstance.setText(Version.getSingleton().getProperty("substance"));
        jlbSubstanceC.setText(Version.getSingleton().getProperty("substance_copyright"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jlbFreeMarker = new javax.swing.JLabel();
        jlbFreeMarkerC = new javax.swing.JLabel();
        jlbJDom = new javax.swing.JLabel();
        jlbJDomC = new javax.swing.JLabel();
        jlbJCommon = new javax.swing.JLabel();
        jlbJCommonC = new javax.swing.JLabel();
        jlbSubstance = new javax.swing.JLabel();
        jlbSubstanceC = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jlbNom = new javax.swing.JLabel();
        jlbVersion = new javax.swing.JLabel();
        jlbDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A propos de");
        setResizable(false);
        setUndecorated(true);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(8, 1, 1, 1));

        jlbFreeMarker.setFont(new java.awt.Font("Tahoma", 0, 12));
        jlbFreeMarker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbFreeMarker.setText("FreeMarker");
        jPanel2.add(jlbFreeMarker);

        jlbFreeMarkerC.setFont(new java.awt.Font("Tahoma", 0, 10));
        jlbFreeMarkerC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbFreeMarkerC.setText("FreeMarker COpyright");
        jPanel2.add(jlbFreeMarkerC);

        jlbJDom.setFont(new java.awt.Font("Tahoma", 0, 12));
        jlbJDom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbJDom.setText("Jdom");
        jPanel2.add(jlbJDom);

        jlbJDomC.setFont(new java.awt.Font("Tahoma", 0, 10));
        jlbJDomC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbJDomC.setText("Jdom");
        jPanel2.add(jlbJDomC);

        jlbJCommon.setFont(new java.awt.Font("Tahoma", 0, 12));
        jlbJCommon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbJCommon.setText("JCommon");
        jPanel2.add(jlbJCommon);

        jlbJCommonC.setFont(new java.awt.Font("Tahoma", 0, 10));
        jlbJCommonC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbJCommonC.setText("JCommon");
        jPanel2.add(jlbJCommonC);

        jlbSubstance.setFont(new java.awt.Font("Tahoma", 0, 12));
        jlbSubstance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSubstance.setText("Substance");
        jPanel2.add(jlbSubstance);

        jlbSubstanceC.setFont(new java.awt.Font("Tahoma", 0, 10));
        jlbSubstanceC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSubstanceC.setText("Substance");
        jPanel2.add(jlbSubstanceC);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(3, 0));

        jlbNom.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbNom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbNom.setText("Nom");
        jPanel4.add(jlbNom);

        jlbVersion.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbVersion.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbVersion.setText("Version");
        jPanel4.add(jlbVersion);

        jlbDate.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbDate.setText("Date");
        jPanel4.add(jlbDate);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jlbDate;
    private javax.swing.JLabel jlbFreeMarker;
    private javax.swing.JLabel jlbFreeMarkerC;
    private javax.swing.JLabel jlbJCommon;
    private javax.swing.JLabel jlbJCommonC;
    private javax.swing.JLabel jlbJDom;
    private javax.swing.JLabel jlbJDomC;
    private javax.swing.JLabel jlbNom;
    private javax.swing.JLabel jlbSubstance;
    private javax.swing.JLabel jlbSubstanceC;
    private javax.swing.JLabel jlbVersion;
    // End of variables declaration//GEN-END:variables

}
