/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tourma.views.round;

import java.awt.Color;
import tourma.data.Match;
import tourma.data.Tournament;
import tourma.data.Value;

/**
 *
 * @author WFMJ7631
 */
public class JPNMatch extends javax.swing.JPanel {

    /**
     * Creates new form JPNMatch
     */
    public JPNMatch(final Match m,final boolean winner) {
        initComponents();

        jlbPlayer1.setText(m.mCoach1.mName);
        jlbPlayer2.setText(m.mCoach2.mName);

        jlbPlayer1.setBackground(m.mCoach1.mColor);
        jlbPlayer2.setBackground(m.mCoach2.mColor);
        
        jPanel2.setBackground(m.mCoach1.mColor);
        jPanel4.setBackground(m.mCoach2.mColor);
        
        final Value v=m.mValues.get(Tournament.getTournament().getParams().mCriterias.get(0));
        if ((v.mValue1 == -1)||(v.mValue2 == -1)) {
            jlbScore1.setText(java.util.ResourceBundle.getBundle("tourma/languages/language").getString(""));
            jlbScore2.setText(java.util.ResourceBundle.getBundle("tourma/languages/language").getString(""));
        } else {
            jlbScore1.setText(Integer.toString(v.mValue1));
            jlbScore2.setText(Integer.toString(v.mValue2));
        }        

        if (!winner)
        {
            jPanel1.setBackground(Color.LIGHT_GRAY);
            //jPanel2.setBackground(Color.LIGHT_GRAY);
            //jPanel4.setBackground(Color.LIGHT_GRAY);
            this.setBackground(Color.LIGHT_GRAY);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlbPlayer1 = new javax.swing.JLabel();
        jlbScore1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jlbPlayer2 = new javax.swing.JLabel();
        jlbScore2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(100, 50));
        setMinimumSize(new java.awt.Dimension(100, 50));
        setPreferredSize(new java.awt.Dimension(150, 50));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(150, 25));
        jPanel2.setMinimumSize(new java.awt.Dimension(150, 25));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jlbPlayer1.setBackground(new java.awt.Color(255, 255, 255));
        jlbPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tourma/languages/language"); // NOI18N
        jlbPlayer1.setText(bundle.getString("PLAYER 1")); // NOI18N
        jlbPlayer1.setMaximumSize(new java.awt.Dimension(135, 25));
        jlbPlayer1.setMinimumSize(new java.awt.Dimension(135, 25));
        jlbPlayer1.setPreferredSize(new java.awt.Dimension(135, 25));
        jPanel2.add(jlbPlayer1, java.awt.BorderLayout.WEST);

        jlbScore1.setBackground(new java.awt.Color(255, 255, 255));
        jlbScore1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbScore1.setText(bundle.getString("0")); // NOI18N
        jlbScore1.setMaximumSize(new java.awt.Dimension(15, 25));
        jlbScore1.setMinimumSize(new java.awt.Dimension(15, 25));
        jlbScore1.setPreferredSize(new java.awt.Dimension(15, 25));
        jPanel2.add(jlbScore1, java.awt.BorderLayout.EAST);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setMinimumSize(new java.awt.Dimension(5, 25));
        jSeparator2.setPreferredSize(new java.awt.Dimension(5, 25));
        jPanel2.add(jSeparator2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);
        jPanel1.add(jSeparator1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setMaximumSize(new java.awt.Dimension(150, 25));
        jPanel4.setMinimumSize(new java.awt.Dimension(150, 25));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jlbPlayer2.setBackground(new java.awt.Color(255, 255, 255));
        jlbPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbPlayer2.setText(bundle.getString("PLAYER 2")); // NOI18N
        jlbPlayer2.setMaximumSize(new java.awt.Dimension(135, 25));
        jlbPlayer2.setMinimumSize(new java.awt.Dimension(135, 25));
        jlbPlayer2.setPreferredSize(new java.awt.Dimension(135, 25));
        jPanel4.add(jlbPlayer2, java.awt.BorderLayout.WEST);

        jlbScore2.setBackground(new java.awt.Color(255, 255, 255));
        jlbScore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbScore2.setText(bundle.getString("0")); // NOI18N
        jlbScore2.setMaximumSize(new java.awt.Dimension(15, 25));
        jlbScore2.setMinimumSize(new java.awt.Dimension(15, 25));
        jlbScore2.setPreferredSize(new java.awt.Dimension(15, 25));
        jPanel4.add(jlbScore2, java.awt.BorderLayout.EAST);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setMinimumSize(new java.awt.Dimension(5, 25));
        jSeparator3.setPreferredSize(new java.awt.Dimension(5, 25));
        jPanel4.add(jSeparator3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(bundle.getString("#")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(10, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(10, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(10, 50));
        add(jLabel3, java.awt.BorderLayout.WEST);
        jLabel3.getAccessibleContext().setAccessibleName(bundle.getString("JLBID")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlbPlayer1;
    private javax.swing.JLabel jlbPlayer2;
    private javax.swing.JLabel jlbScore1;
    private javax.swing.JLabel jlbScore2;
    // End of variables declaration//GEN-END:variables
}
