/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teamma.views;

import java.awt.Dimension;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Vector;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import teamma.data.Player;
import teamma.data.PlayerType;
import teamma.data.Roster;
import teamma.data.Skill;
import teamma.data.lrb;
import teamma.data.RosterType;
import teamma.tableModel.mjtTeamPlayers;
import tourma.MainFrame;

/**
 *
 * @author WFMJ7631
 */
public class JdgRoster extends javax.swing.JDialog {
    
    Roster _data = null;

    /**
     * Creates new form JdgRoster
     */
    public JdgRoster(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        _data = new Roster();
        initComponents();
        
        
        this.setPreferredSize(new Dimension(1024, 768));
        pack();
        
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();
        
        this.setSize(1024, 768);
        
        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }
        
        update();
        jbtAddSkill.setEnabled(false);
        jbtRemoveSkill.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpnTitle = new javax.swing.JPanel();
        jlbTeamName = new javax.swing.JLabel();
        jlbRosterType = new javax.swing.JLabel();
        jlbCoachName = new javax.swing.JLabel();
        jpnCenter = new javax.swing.JPanel();
        jxtpCenter = new org.jdesktop.swingx.JXTitledPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbPlayers = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbtAdd = new javax.swing.JButton();
        jbtRemove = new javax.swing.JButton();
        jbtAddSkill = new javax.swing.JButton();
        jbtRemoveSkill = new javax.swing.JButton();
        jpnCenterSouth = new javax.swing.JPanel();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jslExtraReroll = new javax.swing.JSlider();
        jlbNbExtraReroll = new javax.swing.JLabel();
        jlbX = new javax.swing.JLabel();
        jlbPriceExtraReroll = new javax.swing.JLabel();
        jlbX1 = new javax.swing.JLabel();
        jlbCostExtraReroll = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jslBribeTheRef = new javax.swing.JSlider();
        jlbNbBribeTheRef = new javax.swing.JLabel();
        jlbX2 = new javax.swing.JLabel();
        jlbPriceBribeTheRef = new javax.swing.JLabel();
        jlbX3 = new javax.swing.JLabel();
        jlbCostBribeTheRef = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jslLocalApothecary = new javax.swing.JSlider();
        jlbNbLocalApothecary = new javax.swing.JLabel();
        jlbX4 = new javax.swing.JLabel();
        jlbPriceLocalApothecary = new javax.swing.JLabel();
        jlbX5 = new javax.swing.JLabel();
        jlbCostLocalApothecary = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jslWizard = new javax.swing.JSlider();
        jlbNbWizard = new javax.swing.JLabel();
        jlbX6 = new javax.swing.JLabel();
        jlbPriceWizard = new javax.swing.JLabel();
        jlbX7 = new javax.swing.JLabel();
        jlbCostWizard = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jslIgor = new javax.swing.JSlider();
        jlbNbIgor = new javax.swing.JLabel();
        jlbX8 = new javax.swing.JLabel();
        jlbPriceIgor = new javax.swing.JLabel();
        jlbX9 = new javax.swing.JLabel();
        jlbCostIgor = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jslCardBudget = new javax.swing.JSlider();
        jlbX11 = new javax.swing.JLabel();
        jlbCostCard = new javax.swing.JLabel();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jbtAddStar = new javax.swing.JButton();
        jbtRemoveStar = new javax.swing.JButton();
        jpnSouth = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlbInducements1 = new javax.swing.JLabel();
        jtbGoods = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jlbIcon = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 724));

        jpnTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jpnTitle.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        jlbTeamName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbTeamName.setText("TeamName");
        jpnTitle.add(jlbTeamName);

        jlbRosterType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbRosterType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbRosterType.setText("Roster: Unknown");
        jlbRosterType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbRosterTypeMouseClicked(evt);
            }
        });
        jpnTitle.add(jlbRosterType);

        jlbCoachName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbCoachName.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jlbCoachName.setText("Coach: Unknown");
        jpnTitle.add(jlbCoachName);

        getContentPane().add(jpnTitle, java.awt.BorderLayout.NORTH);

        jpnCenter.setMinimumSize(new java.awt.Dimension(640, 200));
        jpnCenter.setPreferredSize(new java.awt.Dimension(320, 450));
        jpnCenter.setLayout(new java.awt.BorderLayout());

        jxtpCenter.setTitle("Players");
        jxtpCenter.setName("Players"); // NOI18N
        jxtpCenter.setPreferredSize(new java.awt.Dimension(800, 400));
        jxtpCenter.getContentContainer().setLayout(new java.awt.BorderLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(520, 100));

        jtbPlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbPlayers.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtbPlayers.setPreferredSize(null);
        jtbPlayers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbPlayersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbPlayers);

        jxtpCenter.getContentContainer().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel2.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jbtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Add.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tourma/languages/language"); // NOI18N
        jbtAdd.setText(bundle.getString("Player")); // NOI18N
        jbtAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtAdd.setPreferredSize(new java.awt.Dimension(100, 60));
        jbtAdd.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        jPanel2.add(jbtAdd);

        jbtRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Close.png"))); // NOI18N
        jbtRemove.setText(bundle.getString("Player")); // NOI18N
        jbtRemove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtRemove.setPreferredSize(new java.awt.Dimension(100, 60));
        jbtRemove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(jbtRemove);

        jbtAddSkill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Add.png"))); // NOI18N
        jbtAddSkill.setText(bundle.getString("Skill")); // NOI18N
        jbtAddSkill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtAddSkill.setPreferredSize(new java.awt.Dimension(100, 60));
        jbtAddSkill.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbtAddSkill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAddSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddSkillActionPerformed(evt);
            }
        });
        jPanel2.add(jbtAddSkill);

        jbtRemoveSkill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Close.png"))); // NOI18N
        jbtRemoveSkill.setText(bundle.getString("Skill")); // NOI18N
        jbtRemoveSkill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtRemoveSkill.setPreferredSize(new java.awt.Dimension(100, 60));
        jbtRemoveSkill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtRemoveSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveSkillActionPerformed(evt);
            }
        });
        jPanel2.add(jbtRemoveSkill);

        jxtpCenter.getContentContainer().add(jPanel2, java.awt.BorderLayout.WEST);

        jpnCenter.add(jxtpCenter, java.awt.BorderLayout.CENTER);

        jpnCenterSouth.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jXTaskPane2.setCollapsed(true);
        jXTaskPane2.setTitle("Primes de match");
        jXTaskPane2.getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Mercenaires et Champions"))); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 220));
        jPanel8.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Extra Reroll");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel1.add(jLabel2);

        jslExtraReroll.setMajorTickSpacing(2);
        jslExtraReroll.setMaximum(4);
        jslExtraReroll.setMinorTickSpacing(1);
        jslExtraReroll.setPaintTicks(true);
        jslExtraReroll.setSnapToTicks(true);
        jslExtraReroll.setValue(0);
        jslExtraReroll.setMaximumSize(new java.awt.Dimension(50, 23));
        jslExtraReroll.setMinimumSize(new java.awt.Dimension(30, 23));
        jslExtraReroll.setPreferredSize(new java.awt.Dimension(50, 23));
        jslExtraReroll.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jslExtraRerollStateChanged(evt);
            }
        });
        jPanel1.add(jslExtraReroll);

        jlbNbExtraReroll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNbExtraReroll.setLabelFor(jslExtraReroll);
        jlbNbExtraReroll.setText("0");
        jlbNbExtraReroll.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel1.add(jlbNbExtraReroll);

        jlbX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX.setText("x");
        jlbX.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel1.add(jlbX);

        jlbPriceExtraReroll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPriceExtraReroll.setText("100 000");
        jlbPriceExtraReroll.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel1.add(jlbPriceExtraReroll);

        jlbX1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX1.setText("=");
        jlbX1.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel1.add(jlbX1);

        jlbCostExtraReroll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCostExtraReroll.setText("0");
        jlbCostExtraReroll.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel1.add(jlbCostExtraReroll);

        jPanel8.add(jPanel1);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Bribe the Ref");
        jLabel3.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel9.add(jLabel3);

        jslBribeTheRef.setMajorTickSpacing(2);
        jslBribeTheRef.setMaximum(4);
        jslBribeTheRef.setMinorTickSpacing(1);
        jslBribeTheRef.setPaintTicks(true);
        jslBribeTheRef.setSnapToTicks(true);
        jslBribeTheRef.setValue(0);
        jslBribeTheRef.setMaximumSize(new java.awt.Dimension(50, 23));
        jslBribeTheRef.setMinimumSize(new java.awt.Dimension(30, 23));
        jslBribeTheRef.setPreferredSize(new java.awt.Dimension(50, 23));
        jslBribeTheRef.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jslBribeTheRefStateChanged(evt);
            }
        });
        jPanel9.add(jslBribeTheRef);

        jlbNbBribeTheRef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNbBribeTheRef.setLabelFor(jslBribeTheRef);
        jlbNbBribeTheRef.setText("0");
        jlbNbBribeTheRef.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jlbNbBribeTheRef);

        jlbX2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX2.setText("x");
        jlbX2.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jlbX2);

        jlbPriceBribeTheRef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPriceBribeTheRef.setText("100 000");
        jlbPriceBribeTheRef.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel9.add(jlbPriceBribeTheRef);

        jlbX3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX3.setText("=");
        jlbX3.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel9.add(jlbX3);

        jlbCostBribeTheRef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCostBribeTheRef.setText("0");
        jlbCostBribeTheRef.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel9.add(jlbCostBribeTheRef);

        jPanel8.add(jPanel9);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Local Apothecary");
        jLabel4.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel10.add(jLabel4);

        jslLocalApothecary.setMajorTickSpacing(2);
        jslLocalApothecary.setMaximum(4);
        jslLocalApothecary.setMinorTickSpacing(1);
        jslLocalApothecary.setPaintTicks(true);
        jslLocalApothecary.setSnapToTicks(true);
        jslLocalApothecary.setValue(0);
        jslLocalApothecary.setMaximumSize(new java.awt.Dimension(50, 23));
        jslLocalApothecary.setMinimumSize(new java.awt.Dimension(30, 23));
        jslLocalApothecary.setPreferredSize(new java.awt.Dimension(50, 23));
        jslLocalApothecary.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jslLocalApothecaryStateChanged(evt);
            }
        });
        jPanel10.add(jslLocalApothecary);

        jlbNbLocalApothecary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNbLocalApothecary.setLabelFor(jslLocalApothecary);
        jlbNbLocalApothecary.setText("0");
        jlbNbLocalApothecary.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel10.add(jlbNbLocalApothecary);

        jlbX4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX4.setText("x");
        jlbX4.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel10.add(jlbX4);

        jlbPriceLocalApothecary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPriceLocalApothecary.setText("100 000");
        jlbPriceLocalApothecary.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel10.add(jlbPriceLocalApothecary);

        jlbX5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX5.setText("=");
        jlbX5.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel10.add(jlbX5);

        jlbCostLocalApothecary.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCostLocalApothecary.setText("0");
        jlbCostLocalApothecary.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel10.add(jlbCostLocalApothecary);

        jPanel8.add(jPanel10);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Wizard");
        jLabel5.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel11.add(jLabel5);

        jslWizard.setMajorTickSpacing(1);
        jslWizard.setMaximum(1);
        jslWizard.setPaintTicks(true);
        jslWizard.setSnapToTicks(true);
        jslWizard.setValue(0);
        jslWizard.setMaximumSize(new java.awt.Dimension(50, 23));
        jslWizard.setMinimumSize(new java.awt.Dimension(30, 23));
        jslWizard.setPreferredSize(new java.awt.Dimension(50, 23));
        jslWizard.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jslWizardStateChanged(evt);
            }
        });
        jPanel11.add(jslWizard);

        jlbNbWizard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNbWizard.setLabelFor(jslWizard);
        jlbNbWizard.setText("0");
        jlbNbWizard.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel11.add(jlbNbWizard);

        jlbX6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX6.setText("x");
        jlbX6.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel11.add(jlbX6);

        jlbPriceWizard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPriceWizard.setText("150 000");
        jlbPriceWizard.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel11.add(jlbPriceWizard);

        jlbX7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX7.setText("=");
        jlbX7.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel11.add(jlbX7);

        jlbCostWizard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCostWizard.setText("0");
        jlbCostWizard.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel11.add(jlbCostWizard);

        jPanel8.add(jPanel11);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Igor");
        jLabel6.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel12.add(jLabel6);

        jslIgor.setMajorTickSpacing(1);
        jslIgor.setMaximum(1);
        jslIgor.setMinorTickSpacing(1);
        jslIgor.setPaintTicks(true);
        jslIgor.setSnapToTicks(true);
        jslIgor.setValue(0);
        jslIgor.setMaximumSize(new java.awt.Dimension(50, 23));
        jslIgor.setMinimumSize(new java.awt.Dimension(30, 23));
        jslIgor.setPreferredSize(new java.awt.Dimension(50, 23));
        jslIgor.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jslIgorStateChanged(evt);
            }
        });
        jPanel12.add(jslIgor);

        jlbNbIgor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbNbIgor.setLabelFor(jslIgor);
        jlbNbIgor.setText("0");
        jlbNbIgor.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel12.add(jlbNbIgor);

        jlbX8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX8.setText("x");
        jlbX8.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel12.add(jlbX8);

        jlbPriceIgor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbPriceIgor.setText("100 000");
        jlbPriceIgor.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel12.add(jlbPriceIgor);

        jlbX9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX9.setText("=");
        jlbX9.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel12.add(jlbX9);

        jlbCostIgor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCostIgor.setText("0");
        jlbCostIgor.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel12.add(jlbCostIgor);

        jPanel8.add(jPanel12);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Card Budget");
        jLabel7.setPreferredSize(new java.awt.Dimension(120, 14));
        jPanel13.add(jLabel7);

        jslCardBudget.setMajorTickSpacing(200000);
        jslCardBudget.setMaximum(1000000);
        jslCardBudget.setMinorTickSpacing(50000);
        jslCardBudget.setPaintTicks(true);
        jslCardBudget.setSnapToTicks(true);
        jslCardBudget.setValue(0);
        jslCardBudget.setMaximumSize(new java.awt.Dimension(50, 23));
        jslCardBudget.setMinimumSize(new java.awt.Dimension(30, 23));
        jslCardBudget.setPreferredSize(new java.awt.Dimension(155, 23));
        jslCardBudget.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jslCardBudgetStateChanged(evt);
            }
        });
        jPanel13.add(jslCardBudget);

        jlbX11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbX11.setText("=");
        jlbX11.setPreferredSize(new java.awt.Dimension(10, 14));
        jPanel13.add(jlbX11);

        jlbCostCard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbCostCard.setLabelFor(jslCardBudget);
        jlbCostCard.setText("0");
        jlbCostCard.setPreferredSize(new java.awt.Dimension(70, 14));
        jPanel13.add(jlbCostCard);

        jPanel8.add(jPanel13);

        jXTaskPane2.getContentPane().add(jPanel8, java.awt.BorderLayout.CENTER);

        jpnCenterSouth.add(jXTaskPane2);

        jXTaskPane1.setCollapsed(true);
        jXTaskPane1.setTitle("Star Players");
        jXTaskPane1.getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Mercenaires et Champions"))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(160, 150));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setMinimumSize(new java.awt.Dimension(120, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 160));
        jPanel5.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jbtAddStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Add.png"))); // NOI18N
        jbtAddStar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtAddStar.setLabel(bundle.getString("Star")); // NOI18N
        jbtAddStar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtAddStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddStarActionPerformed(evt);
            }
        });
        jPanel5.add(jbtAddStar);

        jbtRemoveStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Close.png"))); // NOI18N
        jbtRemoveStar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtRemoveStar.setLabel(bundle.getString("Star")); // NOI18N
        jbtRemoveStar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtRemoveStar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveStarActionPerformed(evt);
            }
        });
        jPanel5.add(jbtRemoveStar);

        jPanel4.add(jPanel5, java.awt.BorderLayout.WEST);

        jXTaskPane1.getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jpnCenterSouth.add(jXTaskPane1);

        jpnCenter.add(jpnCenterSouth, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jpnCenter, java.awt.BorderLayout.CENTER);

        jpnSouth.setPreferredSize(new java.awt.Dimension(640, 200));
        jpnSouth.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(300, 150));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jlbInducements1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbInducements1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbInducements1.setText(bundle.getString("Biens d'équipe")); // NOI18N
        jlbInducements1.setFocusable(false);
        jlbInducements1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jlbInducements1, java.awt.BorderLayout.NORTH);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbGoods.setViewportView(jTable4);

        jPanel3.add(jtbGoods, java.awt.BorderLayout.CENTER);

        jpnSouth.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel6.setPreferredSize(new java.awt.Dimension(640, 30));

        jbtOK.setText("OK");
        jPanel6.add(jbtOK);

        jpnSouth.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jlbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teamma/images/what.png"))); // NOI18N
        jlbIcon.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel7.add(jlbIcon);

        jpnSouth.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpnSouth, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        if (_data._roster == null) {
            JOptionPane.showMessageDialog(this, "Roster type not selected, please click on roster");
        } else {
            int i;
            /**
             * Build Avilable Positions
             */
            Vector<String> positions = new Vector<String>();
            for (i = 0; i < _data._roster._player_types.size(); i++) {
                PlayerType pt = _data._roster._player_types.get(i);
                /*
                 * Count the number of player possible
                 */
                int limit = pt._limit;
                int j;
                for (j = 0; j < _data._players.size(); j++) {
                    if (_data._players.get(j)._playertype == pt) {
                        limit--;
                    }
                }
                if (limit > 0) {
                    positions.add(pt._position);
                }
            }
            
            String input = (String) JOptionPane.showInputDialog(this,
                    "Choisissez le type de joueur", "Choix du joueur", JOptionPane.INFORMATION_MESSAGE,
                    null, positions.toArray(), "Amazons");
            PlayerType pt = _data._roster.getPlayerType(input);
            Player p = new Player(pt);
            
            _data._players.add(p);
        }
        
        
        update();
    }//GEN-LAST:event_jbtAddActionPerformed
    
    private void jbtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveActionPerformed
        /* Get Selected line */
        int selectedLine = jtbPlayers.getSelectedRow();
        if (selectedLine > -1) {
            _data._players.remove(selectedLine);
            update();
        }
        
    }//GEN-LAST:event_jbtRemoveActionPerformed
    
    private void jbtAddStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddStarActionPerformed
    }//GEN-LAST:event_jbtAddStarActionPerformed
    
    private void jbtRemoveStarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveStarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtRemoveStarActionPerformed
    
    private void jlbRosterTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbRosterTypeMouseClicked
        
        Vector<String> rosterlist = lrb.getLRB().getRosterTypeListAsString();
        String input = (String) JOptionPane.showInputDialog(this,
                "Choisissez le roster", "Choix du roster", JOptionPane.INFORMATION_MESSAGE,
                null, rosterlist.toArray(), "Amazons");
        RosterType rt = lrb.getLRB().getRosterType(input);
        if (rt != null) {
            if (_data._roster != rt) {
                _data._roster = rt;
                _data._players.removeAllElements();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erreur de choix du roster: " + input);
        }
        
        jlbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teamma/images/" + rt._image))); // NOI18N
        update();
        
    }//GEN-LAST:event_jlbRosterTypeMouseClicked
    
    private void jbtRemoveSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveSkillActionPerformed
        int index = jtbPlayers.getSelectedRow();
        if (index > -1) {
            Vector<String> skills = new Vector<String>();
            Player p = _data._players.get(index);
            if (p._skills.size() > 0) {
                int i;
                for (i = 0; i < p._skills.size(); i++) {
                    Skill s = p._skills.get(i);
                    skills.add(s._name);
                }
                
                Object choice = JOptionPane.showInputDialog(MainFrame.getMainFrame(), "Select skill to remove", "Skill", JOptionPane.INFORMATION_MESSAGE, null, skills.toArray(), null);
                if (choice != null) {
                    
                    for (i = 0; i < p._skills.size(); i++) {
                        if (p._skills.get(i)._name.equals(choice)) {
                            p._skills.remove(i);
                            break;
                        }
                    }
                }
            }
        }
        update();
    }//GEN-LAST:event_jbtRemoveSkillActionPerformed
    
    private void jbtAddSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddSkillActionPerformed
        int index = jtbPlayers.getSelectedRow();
        if (index > -1) {
            JdgSelectSkill jdg = new JdgSelectSkill(MainFrame.getMainFrame(), true, _data._players.get(index));
            jdg.setVisible(true);
        }
        update();
    }//GEN-LAST:event_jbtAddSkillActionPerformed
    
    private void jtbPlayersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbPlayersMouseClicked
        jbtAddSkill.setEnabled(jtbPlayers.getSelectedRow() > -1);
        boolean removable = false;
        int i = jtbPlayers.getSelectedRow();
        if (jtbPlayers.getSelectedRow() > -1) {
            if (_data._players.get(jtbPlayers.getSelectedRow())._skills.size() > 0) {
                removable = true;
            }
        }
        jbtRemoveSkill.setEnabled(removable);
    }//GEN-LAST:event_jtbPlayersMouseClicked
    
    private void jslExtraRerollStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslExtraRerollStateChanged
        _data._extrarerolls = jslExtraReroll.getValue();
        update();
    }//GEN-LAST:event_jslExtraRerollStateChanged
    
    private void jslBribeTheRefStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslBribeTheRefStateChanged
        _data._corruptions = jslBribeTheRef.getValue();
        update();
    }//GEN-LAST:event_jslBribeTheRefStateChanged
    
    private void jslLocalApothecaryStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslLocalApothecaryStateChanged
        _data._localapothecary = jslLocalApothecary.getValue();
        update();
    }//GEN-LAST:event_jslLocalApothecaryStateChanged
    
    private void jslWizardStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslWizardStateChanged
        _data._wizard = jslWizard.getValue() == 1;
        update();
    }//GEN-LAST:event_jslWizardStateChanged
    
    private void jslIgorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslIgorStateChanged
        _data._igor = jslIgor.getValue() == 1;
        update();
    }//GEN-LAST:event_jslIgorStateChanged
    
    private void jslCardBudgetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jslCardBudgetStateChanged
        _data._cards = jslCardBudget.getValue();
        update();
    }//GEN-LAST:event_jslCardBudgetStateChanged
    
    private void update() {
        if (_data._roster != null) {
            jlbRosterType.setText("Roster: " + _data._roster._name);
        } else {
            jlbRosterType.setText("Roster: Unknown");
        }
        
        jbtAdd.setEnabled(_data._champions.size() + _data._players.size() < 16);
        jbtRemove.setEnabled(_data._players.size() > 0);
        
        mjtTeamPlayers playersModel = new mjtTeamPlayers(_data._players);
        
        if (_data._roster != null) {
            jlbPriceBribeTheRef.setText(Integer.toString(_data._roster._bribe_cost));
        }
        
        jtbPlayers.setModel(playersModel);
        jtbPlayers.getColumnModel().getColumn(0).setMinWidth(5);
        jtbPlayers.getColumnModel().getColumn(1).setMinWidth(80);
        jtbPlayers.getColumnModel().getColumn(2).setMinWidth(80);
        jtbPlayers.getColumnModel().getColumn(3).setMinWidth(5);
        jtbPlayers.getColumnModel().getColumn(4).setMinWidth(5);
        jtbPlayers.getColumnModel().getColumn(5).setMinWidth(5);
        jtbPlayers.getColumnModel().getColumn(6).setMinWidth(5);
        jtbPlayers.getColumnModel().getColumn(7).setMinWidth(200);
        jtbPlayers.getColumnModel().getColumn(8).setMinWidth(10);
        jtbPlayers.getColumnModel().getColumn(9).setMinWidth(10);
        jtbPlayers.getColumnModel().getColumn(10).setMinWidth(10);
        jtbPlayers.getColumnModel().getColumn(11).setMinWidth(10);
        
        jtbPlayers.getColumnModel().getColumn(7).addPropertyChangeListener(new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent evt) {
                if (evt.getPropertyName().equals("width")) {
                    jtbPlayers.setRowHeight(1);
                    mjtTeamPlayers playersModel = new mjtTeamPlayers(_data._players);
                    jtbPlayers.setDefaultRenderer(String.class, playersModel);
                }
            }
        });
        
        jtbPlayers.setDefaultRenderer(Integer.class, playersModel);
        jtbPlayers.setDefaultRenderer(String.class, playersModel);
        
        jlbPriceExtraReroll.setText(Integer.toString(RosterType._extra_reroll_cost));
        jlbNbExtraReroll.setText(Integer.toString(_data._extrarerolls));
        jlbCostExtraReroll.setText(Integer.toString(_data._extrarerolls * RosterType._extra_reroll_cost));
        
        if (_data._wizard) {
            jlbNbWizard.setText("1");
            jlbCostWizard.setText(Integer.toString(RosterType._wizard_cost));
        } else {
            jlbNbWizard.setText("0");
            jlbCostWizard.setText("0");
        }
        jlbPriceWizard.setText(Integer.toString(RosterType._wizard_cost));
        
        jlbNbBribeTheRef.setText(Integer.toString(_data._corruptions));
        if (_data._roster != null) {
            jlbCostBribeTheRef.setText(Integer.toString(_data._corruptions * _data._roster._bribe_cost));
        }
        
        boolean canHaveApo = false;
        if (_data._roster != null) {
            if (_data._roster._apothecary) {
                canHaveApo = true;
            }
        }
        
        jlbCostLocalApothecary.setEnabled(canHaveApo);
        jslLocalApothecary.setEnabled(canHaveApo);
        jlbCostLocalApothecary.setEnabled(canHaveApo);
        jlbPriceLocalApothecary.setEnabled(canHaveApo);
        jlbNbLocalApothecary.setEnabled(canHaveApo);
        jlbX4.setEnabled(canHaveApo);
        
        if (!canHaveApo) {
            _data._localapothecary = 0;
            jlbCostLocalApothecary.setText("0");
            jlbPriceLocalApothecary.setText("100000");
            jlbNbLocalApothecary.setText("0");
            jslLocalApothecary.setValue(0);
        } else {
            jlbNbLocalApothecary.setText(Integer.toString(_data._localapothecary));
            jlbCostLocalApothecary.setText(Integer.toString(_data._localapothecary * RosterType._local_apo_cost));
            jlbPriceLocalApothecary.setText(Integer.toString(RosterType._local_apo_cost));
        }
        
        boolean canIgor = false;
        if (_data._roster != null) {
            if (_data._roster._igor) {
                canIgor = true;
            }
        }
        
        jlbCostIgor.setEnabled(canIgor);
        jslIgor.setEnabled(canIgor);
        jlbCostIgor.setEnabled(canIgor);
        jlbPriceIgor.setEnabled(canIgor);
        jlbNbIgor.setEnabled(canIgor);
        jlbX6.setEnabled(canIgor);
        
        if (!canIgor) {
            _data._igor = false;
            jlbCostIgor.setText("0");
            jlbPriceIgor.setText("100000");
            jlbNbIgor.setText("0");
            jslIgor.setValue(0);
        } else {
            
            jlbNbIgor.setText(Integer.toString(jslIgor.getValue()));
            jlbCostIgor.setText(Integer.toString(jslIgor.getValue() * RosterType._igor_cost));
            jlbPriceIgor.setText(Integer.toString(RosterType._igor_cost));
        }
        
        jlbCostCard.setText(Integer.toString(_data._cards));
//        jlbCardBudget.setText(Integer.toString(_data._cards));
        if (_data._roster != null) {
            jlbCostBribeTheRef.setText(Integer.toString(_data._corruptions * _data._roster._bribe_cost));
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtAddSkill;
    private javax.swing.JButton jbtAddStar;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtRemove;
    private javax.swing.JButton jbtRemoveSkill;
    private javax.swing.JButton jbtRemoveStar;
    private javax.swing.JLabel jlbCoachName;
    private javax.swing.JLabel jlbCostBribeTheRef;
    private javax.swing.JLabel jlbCostCard;
    private javax.swing.JLabel jlbCostExtraReroll;
    private javax.swing.JLabel jlbCostIgor;
    private javax.swing.JLabel jlbCostLocalApothecary;
    private javax.swing.JLabel jlbCostWizard;
    private javax.swing.JLabel jlbIcon;
    private javax.swing.JLabel jlbInducements1;
    private javax.swing.JLabel jlbNbBribeTheRef;
    private javax.swing.JLabel jlbNbExtraReroll;
    private javax.swing.JLabel jlbNbIgor;
    private javax.swing.JLabel jlbNbLocalApothecary;
    private javax.swing.JLabel jlbNbWizard;
    private javax.swing.JLabel jlbPriceBribeTheRef;
    private javax.swing.JLabel jlbPriceExtraReroll;
    private javax.swing.JLabel jlbPriceIgor;
    private javax.swing.JLabel jlbPriceLocalApothecary;
    private javax.swing.JLabel jlbPriceWizard;
    private javax.swing.JLabel jlbRosterType;
    private javax.swing.JLabel jlbTeamName;
    private javax.swing.JLabel jlbX;
    private javax.swing.JLabel jlbX1;
    private javax.swing.JLabel jlbX11;
    private javax.swing.JLabel jlbX2;
    private javax.swing.JLabel jlbX3;
    private javax.swing.JLabel jlbX4;
    private javax.swing.JLabel jlbX5;
    private javax.swing.JLabel jlbX6;
    private javax.swing.JLabel jlbX7;
    private javax.swing.JLabel jlbX8;
    private javax.swing.JLabel jlbX9;
    private javax.swing.JPanel jpnCenter;
    private javax.swing.JPanel jpnCenterSouth;
    private javax.swing.JPanel jpnSouth;
    private javax.swing.JPanel jpnTitle;
    private javax.swing.JSlider jslBribeTheRef;
    private javax.swing.JSlider jslCardBudget;
    private javax.swing.JSlider jslExtraReroll;
    private javax.swing.JSlider jslIgor;
    private javax.swing.JSlider jslLocalApothecary;
    private javax.swing.JSlider jslWizard;
    private javax.swing.JScrollPane jtbGoods;
    private javax.swing.JTable jtbPlayers;
    private org.jdesktop.swingx.JXTitledPanel jxtpCenter;
    // End of variables declaration//GEN-END:variables
}
