/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tourma.views.parameters;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import tourma.data.Group;
import tourma.data.RosterType;
import tourma.data.Tournament;

/**
 *
 * @author WFMJ7631
 */
public final class JPNParamGroup extends javax.swing.JPanel {

    private final Tournament mTournament;

    /**
     * Creates new form JPNParamGroup
     */
    public JPNParamGroup() {

        mTournament = Tournament.getTournament();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    @SuppressFBWarnings({"SIC"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jlsGroups = new javax.swing.JList();
        jPanel19 = new javax.swing.JPanel();
        jbtAddGroup = new javax.swing.JButton();
        jbtRemoveGroup = new javax.swing.JButton();
        jbtRenameGroup = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jlsLeft = new javax.swing.JList();
        jcbGroupLeft = new javax.swing.JComboBox();
        jPanel22 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jbtGroupToRight = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jbtGrouToLeft = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jlsRight = new javax.swing.JList();
        jcbGroupRight = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Liste de groupes"));
        jPanel18.setLayout(new java.awt.BorderLayout(1, 1));

        jlsGroups.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlsGroups.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(jlsGroups);

        jPanel18.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanel19.setLayout(new java.awt.GridLayout(3, 1, 1, 1));

        jbtAddGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Add.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tourma/languages/language"); // NOI18N
        jbtAddGroup.setText(bundle.getString("AJOUTER")); // NOI18N
        jbtAddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddGroupActionPerformed(evt);
            }
        });
        jPanel19.add(jbtAddGroup);

        jbtRemoveGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Close.png"))); // NOI18N
        jbtRemoveGroup.setText(bundle.getString("RETIRER")); // NOI18N
        jbtRemoveGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveGroupActionPerformed(evt);
            }
        });
        jPanel19.add(jbtRemoveGroup);

        jbtRenameGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Swap.png"))); // NOI18N
        jbtRenameGroup.setText(bundle.getString("RENOMMER")); // NOI18N
        jbtRenameGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRenameGroupActionPerformed(evt);
            }
        });
        jPanel19.add(jbtRenameGroup);

        jPanel18.add(jPanel19, java.awt.BorderLayout.LINE_END);

        add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder("Edition des groupes"));
        jPanel20.setLayout(new java.awt.GridLayout(1, 3, 2, 0));

        jPanel21.setLayout(new java.awt.BorderLayout(2, 2));

        jlsLeft.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jlsLeft);

        jPanel21.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jcbGroupLeft.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbGroupLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGroupLeftActionPerformed(evt);
            }
        });
        jPanel21.add(jcbGroupLeft, java.awt.BorderLayout.PAGE_START);

        jPanel20.add(jPanel21);

        jPanel22.setLayout(new java.awt.GridLayout(5, 1));
        jPanel22.add(jPanel24);

        jbtGroupToRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Forward.png"))); // NOI18N
        jbtGroupToRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGroupToRightActionPerformed(evt);
            }
        });
        jPanel22.add(jbtGroupToRight);
        jPanel22.add(jLabel8);

        jbtGrouToLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Backward.png"))); // NOI18N
        jbtGrouToLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGrouToLeftActionPerformed(evt);
            }
        });
        jPanel22.add(jbtGrouToLeft);
        jPanel22.add(jLabel9);

        jPanel20.add(jPanel22);

        jPanel23.setLayout(new java.awt.BorderLayout(2, 2));

        jlsRight.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(jlsRight);

        jPanel23.add(jScrollPane8, java.awt.BorderLayout.CENTER);

        jcbGroupRight.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbGroupRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGroupRightActionPerformed(evt);
            }
        });
        jPanel23.add(jcbGroupRight, java.awt.BorderLayout.PAGE_START);

        jPanel20.add(jPanel23);

        add(jPanel20, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtAddGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddGroupActionPerformed
        final String newGroup = JOptionPane.showInputDialog(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("ENTREZ LE NOM DU NOUVEAU GROUPE"));
        if (newGroup != null) {
            mTournament.addGroup(new Group(newGroup));
            update();
        }
    }//GEN-LAST:event_jbtAddGroupActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtRemoveGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveGroupActionPerformed
        if (jlsGroups.getSelectedIndex() > 0) {
            //final ArrayList<RosterType> rosters = mTournament.getGroup(jlsGroups.getSelectedIndex()).getRosters();
            Group g=mTournament.getGroup(jlsGroups.getSelectedIndex());
            for (int i = 0; i < g.getRosterCount(); i++) {
                mTournament.getGroup(0).addRoster(g.getRoster(i));
            }
            mTournament.removeGroup(jlsGroups.getSelectedIndex());
            update();
        }
    }//GEN-LAST:event_jbtRemoveGroupActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtRenameGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRenameGroupActionPerformed

        if (jlsGroups.getSelectedIndex() >= 0) {
            final String currentName = mTournament.getGroup(jlsGroups.getSelectedIndex()).getName();

            final String newGroup = JOptionPane.showInputDialog(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("ENTREZ LE NOUVEAU NOM DU GROUPE"), currentName);
            if (newGroup != null) {
                mTournament.getGroup(jlsGroups.getSelectedIndex()).setName(newGroup);
                update();
            }
        }
    }//GEN-LAST:event_jbtRenameGroupActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jcbGroupLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGroupLeftActionPerformed
        final DefaultListModel listModel = new DefaultListModel();
        //final ArrayList<RosterType> rosters = mTournament.getGroup(jcbGroupLeft.getSelectedIndex()).getRosters();
        Group g=mTournament.getGroup(jcbGroupLeft.getSelectedIndex());
        for (int i = 0; i < g.getRosterCount(); i++) {
            RosterType r = g.getRoster(i);
            if (r != null) {
                listModel.addElement(r.getName());
            }
        }
        jlsLeft.setModel(listModel);
    }//GEN-LAST:event_jcbGroupLeftActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtGroupToRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGroupToRightActionPerformed

        if (jlsLeft.getSelectedIndex() > -1) {
            final int index = jlsLeft.getSelectedIndex();
            Group g=mTournament.getGroup(jcbGroupLeft.getSelectedIndex());
            final RosterType roster = g.getRoster(index);
            g.removeRoster(roster);
            g.addRoster(roster);
            
            final DefaultListModel listModelLeft = new DefaultListModel();
            for (int i = 0; i < g.getRosterCount(); i++) {
                listModelLeft.addElement(g.getRoster(i).getName());
            }
            jlsLeft.setModel(listModelLeft);

            final DefaultListModel listModelRight = new DefaultListModel();
            g=mTournament.getGroup(jcbGroupRight.getSelectedIndex());
            
            for (int i = 0; i < g.getRosterCount(); i++) {
                listModelRight.addElement(g.getRoster(i).getName());
            }
            jlsRight.setModel(listModelRight);
        }
    }//GEN-LAST:event_jbtGroupToRightActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtGrouToLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGrouToLeftActionPerformed
        if (jlsRight.getSelectedIndex() > -1) {
            final int index = jlsRight.getSelectedIndex();
            Group g=mTournament.getGroup(jcbGroupRight.getSelectedIndex());
            final RosterType roster = g.getRoster(index);
            g.removeRoster(roster);
            g.addRoster(roster);

            
            final DefaultListModel listModelRight = new DefaultListModel();
            for (int i = 0; i < g.getRosterCount(); i++) {
                listModelRight.addElement(g.getRoster(i).getName());
            }
            jlsRight.setModel(listModelRight);

            final DefaultListModel listModelLeft = new DefaultListModel();
            
            //rosters = mTournament.getGroup(jcbGroupLeft.getSelectedIndex()).getRosters();
            g=mTournament.getGroup(jcbGroupLeft.getSelectedIndex());
            for (int i = 0; i < g.getRosterCount(); i++) {
                listModelLeft.addElement(g.getRoster(i).getName());
            }
            jlsLeft.setModel(listModelLeft);
        }
    }//GEN-LAST:event_jbtGrouToLeftActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jcbGroupRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGroupRightActionPerformed
        final DefaultListModel listModel = new DefaultListModel();
        //final ArrayList<RosterType> rosters = mTournament.getGroup(jcbGroupRight.getSelectedIndex()).getRosters();
        Group g=mTournament.getGroup(jcbGroupRight.getSelectedIndex());
        for (int i = 0; i < g.getRosterCount(); i++) {
            RosterType r = g.getRoster(i);
            if (r != null) {
                listModel.addElement(r.getName());
            }
        }
        jlsRight.setModel(listModel);
    }//GEN-LAST:event_jcbGroupRightActionPerformed

    /**
     * Update Panel
     */
    public void update() {

        final boolean bTourStarted = mTournament.getRoundsCount() > 0;
        jbtAddGroup.setEnabled(!bTourStarted);
        jbtRemoveGroup.setEnabled(!bTourStarted);
        jbtRenameGroup.setEnabled(!bTourStarted);
        jbtGrouToLeft.setEnabled(!bTourStarted);
        jbtGroupToRight.setEnabled(!bTourStarted);

        final DefaultListModel groupModel = new DefaultListModel();
        final DefaultComboBoxModel groupsLeftModel = new DefaultComboBoxModel();
        final DefaultComboBoxModel groupsRightModel = new DefaultComboBoxModel();
        for (int i = 0; i < mTournament.getGroupsCount(); i++) {
            groupModel.addElement(mTournament.getGroup(i).getName());
            groupsLeftModel.addElement(mTournament.getGroup(i).getName());
            groupsRightModel.addElement(mTournament.getGroup(i).getName());
        }
        jlsGroups.setModel(groupModel);
        jcbGroupLeft.setModel(groupsLeftModel);
        jcbGroupRight.setModel(groupsRightModel);

        if (mTournament.getGroupsCount() > 0) {
            jcbGroupLeft.setSelectedIndex(0);
            if (mTournament.getGroupsCount() > 1) {
                jcbGroupRight.setSelectedIndex(1);
            } else {
                jcbGroupRight.setSelectedIndex(0);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton jbtAddGroup;
    private javax.swing.JButton jbtGrouToLeft;
    private javax.swing.JButton jbtGroupToRight;
    private javax.swing.JButton jbtRemoveGroup;
    private javax.swing.JButton jbtRenameGroup;
    private javax.swing.JComboBox jcbGroupLeft;
    private javax.swing.JComboBox jcbGroupRight;
    private javax.swing.JList jlsGroups;
    private javax.swing.JList jlsLeft;
    private javax.swing.JList jlsRight;
    // End of variables declaration//GEN-END:variables
    private static final Logger LOG = Logger.getLogger(JPNParamGroup.class.getName());
    
     private void writeObject(java.io.ObjectOutputStream stream) throws java.io.IOException {
        throw new java.io.NotSerializableException(getClass().getName());
    }

    private void readObject(java.io.ObjectInputStream stream) throws java.io.IOException, ClassNotFoundException {
        throw new java.io.NotSerializableException(getClass().getName());
    }
}
