/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgCoach.java
 *
 * Created on 10 mai 2010, 19:37:53
 */
package tourma;

import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import tourma.data.Tournament;
import tourma.data.Coach;
import javax.swing.JOptionPane;
import tourma.data.Match;
import tourma.data.Round;
import tourma.data.Team;
import tourma.tableModel.mjtMatches;

/**
 *
 * @author Frederic Berger
 */
public class jdgPairing extends javax.swing.JDialog {

    Team _team1;
    Team _team2;
    Round _round;
    Vector<String> _items1;
    Vector<String> _items2;
    Hashtable<String, Coach> _coachs;
    Vector<Match> _matchs;

    /** Creates new form jdgCoach */
    public jdgPairing(java.awt.Frame parent, boolean modal, Team team1, Team team2, Round round) {
        super(parent, modal);
        initComponents();

         GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();
        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        _team1 = team1;
        _team2 = team2;
        _coachs = new Hashtable<String, Coach>();

        this.setTitle(team1._name+" vs "+team2._name);

        _round = round;
        _matchs = new Vector<Match>();

        _items1 = new Vector();
        for (int i = 0; i < _team1._coachs.size(); i++) {
            Coach c = _team1._coachs.get(i);
            _items1.add(c._name + " - " + c._team + " - " + c._roster);
            _coachs.put(c._name + " - " + c._team + " - " + c._roster, c);
        }


        _items2 = new Vector();
        for (int i = 0; i < _team1._coachs.size(); i++) {
            Coach c = _team2._coachs.get(i);
            _items2.add(c._name + " - " + c._team + " - " + c._roster);
            _coachs.put(c._name + " - " + c._team + " - " + c._roster, c);
        }

        update();

    }

    private void update() {
        jcbTeam1.setModel(new DefaultComboBoxModel(_items1));
        jcbTeam2.setModel(new DefaultComboBoxModel(_items2));

        mjtMatches model = new mjtMatches(_matchs, true, true, false);
        jtbMatches.setModel(model);
        jtbMatches.setDefaultRenderer(String.class, model);
        jtbMatches.setDefaultRenderer(Integer.class, model);

        jbtOK.setEnabled(_matchs.size() == _team1._coachs.size());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbMatches = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jcbTeam1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jcbTeam2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jbtAdd = new javax.swing.JButton();
        jbtRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jtbMatches.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbMatches);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel2.add(jbtOK);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jcbTeam1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jcbTeam1, java.awt.BorderLayout.WEST);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("vs");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jcbTeam2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jcbTeam2, java.awt.BorderLayout.EAST);

        jbtAdd.setText("Ajoute");
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        jPanel4.add(jbtAdd);

        jbtRemove.setText("Retire");
        jbtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveActionPerformed(evt);
            }
        });
        jPanel4.add(jbtRemove);

        jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        for (int i = 0; i < _matchs.size(); i++) {
            _round.getMatchs().add(_matchs.get(i));
        }
        this.setVisible(false);

    }//GEN-LAST:event_jbtOKActionPerformed

    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed
        if (_items1.size() > 0) {
            Match m = new Match();
            m._coach1 = _coachs.get((String) jcbTeam1.getSelectedItem());
            m._coach2 = _coachs.get((String) jcbTeam2.getSelectedItem());
            _matchs.add(m);
            _items1.remove(jcbTeam1.getSelectedIndex());
            _items2.remove(jcbTeam2.getSelectedIndex());
        }
        update();
    }//GEN-LAST:event_jbtAddActionPerformed

    private void jbtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveActionPerformed

        if (jtbMatches.getSelectedRow() >= 0) {
            Match m = _matchs.get(jtbMatches.getSelectedRow());
            _items1.add(m._coach1._name + " - " + m._coach1._team + " - " + m._coach1._roster);
            _items2.add(m._coach2._name + " - " + m._coach2._team + " - " + m._coach2._roster);
            _matchs.remove(jtbMatches.getSelectedRow());
        }
        update();
    }//GEN-LAST:event_jbtRemoveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtRemove;
    private javax.swing.JComboBox jcbTeam1;
    private javax.swing.JComboBox jcbTeam2;
    private javax.swing.JTable jtbMatches;
    // End of variables declaration//GEN-END:variables
}
