/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JdgCoach.java
 *
 * Created on 10 mai 2010, 19:37:53
 */
package tourma;

import java.awt.BorderLayout;
import java.awt.DisplayMode;
import java.awt.Graphics;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import tourma.data.Clan;
import tourma.data.Team;
import tourma.data.Tournament;
import tourma.tableModel.MjtCoaches;
import tourma.utility.ExtensionFileFilter;

/**
 *
 * @author Frederic Berger
 */
public class JdgTeam extends javax.swing.JDialog {

    boolean mTeamTournament;
    Team mTeam;
    Tournament mTour;

    /**
     *
     * @param parent
     * @param modal
     */
    public JdgTeam(final java.awt.Frame parent, final boolean modal) {
        super(parent, modal);
        initComponents();

        mTour = Tournament.getTournament();
        mTeam = new Team();

        final GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        final GraphicsDevice gs = ge.getDefaultScreenDevice();
        final DisplayMode dmode = gs.getDisplayMode();
        if (dmode != null) {
            final int screenWidth = dmode.getWidth();
            final int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }
        if (mTeam.picture == null) {
            try {
                mTeam.picture = ImageIO.read(getClass().getResource("/tourma/images/flags/france.png"));
            } catch (IOException ex) {
                Logger.getLogger(JdgCoach.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jbtAvatar.setIcon(resize(new ImageIcon(mTeam.picture), 80, 80));

        final DefaultComboBoxModel clanListModel = new DefaultComboBoxModel();
        for (int i = 0; i < Tournament.getTournament().getClans().size(); i++) {
            clanListModel.addElement(Tournament.getTournament().getClans().get(i).getName());
        }
        jcbClan.setModel(clanListModel);

        if ((Tournament.getTournament().getParams().mEnableClans) && (Tournament.getTournament().getClans().size() > 1)) {
            jcbClan.setEnabled(true);
            jLabel2.setEnabled(true);
        }
        else
        {
            jcbClan.setEnabled(false);
            jLabel2.setEnabled(false);
        }


        update();
    }

    /**
     *
     * @param parent
     * @param modal
     * @param team
     */
    public JdgTeam(final java.awt.Frame parent, final boolean modal, final Team team) {
        super(parent, modal);
        initComponents();

        mTour = Tournament.getTournament();
        mTeam = team;

        jtbCoachs.setModel(new MjtCoaches(mTeam.mCoachs));

        final GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        final GraphicsDevice gs = ge.getDefaultScreenDevice();
        final DisplayMode dmode = gs.getDisplayMode();
        if (dmode != null) {
            final int screenWidth = dmode.getWidth();
            final int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        if (mTeam.picture == null) {            
                mTeam.picture = new BufferedImage(96, 96, BufferedImage.TYPE_4BYTE_ABGR);            
        }

        final DefaultComboBoxModel clanListModel = new DefaultComboBoxModel();
        for (int i = 0; i < Tournament.getTournament().getClans().size(); i++) {
            clanListModel.addElement(Tournament.getTournament().getClans().get(i).getName());
        }
        jcbClan.setModel(clanListModel);

        if ((Tournament.getTournament().getParams().mEnableClans) && (Tournament.getTournament().getClans().size() > 1)) {
            jcbClan.setEnabled(true);
            if (team.mClan != null) {
                jcbClan.setSelectedItem(team.mClan.getName());
            }
        }

        jbtAvatar.setIcon(resize(new ImageIcon(mTeam.picture), 80, 80));
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbClan = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jpnCoachButtons = new javax.swing.JPanel();
        jbtAdd = new javax.swing.JButton();
        jbtRemove = new javax.swing.JButton();
        jbtModify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCoachs = new javax.swing.JTable();
        jbtAvatar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tourma/languages/language"); // NOI18N
        jLabel1.setText(bundle.getString("TeamNameKey")); // NOI18N
        jPanel1.add(jLabel1);
        jPanel1.add(jtfNom);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText(bundle.getString("ClanNameKey")); // NOI18N
        jPanel1.add(jLabel2);

        jPanel1.add(jcbClan);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jbtOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Select.png"))); // NOI18N
        jbtOK.setText(bundle.getString("OK")); // NOI18N
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel2.add(jbtOK);

        jbtCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Halt.png"))); // NOI18N
        jbtCancel.setText(bundle.getString("Cancel")); // NOI18N
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jbtCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Coachs"));
        jPanel7.setPreferredSize(new java.awt.Dimension(450, 240));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jbtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Add.png"))); // NOI18N
        jbtAdd.setText(bundle.getString("Add")); // NOI18N
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        jpnCoachButtons.add(jbtAdd);

        jbtRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Close.png"))); // NOI18N
        jbtRemove.setText(bundle.getString("Remove")); // NOI18N
        jbtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveActionPerformed(evt);
            }
        });
        jpnCoachButtons.add(jbtRemove);

        jbtModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Swap.png"))); // NOI18N
        jbtModify.setText(bundle.getString("Modify")); // NOI18N
        jbtModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModifyActionPerformed(evt);
            }
        });
        jpnCoachButtons.add(jbtModify);

        jPanel7.add(jpnCoachButtons, java.awt.BorderLayout.PAGE_START);

        jtbCoachs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbCoachs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtbCoachs);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        jbtAvatar.setMnemonic('A');
        jbtAvatar.setPreferredSize(new java.awt.Dimension(80, 80));
        jbtAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAvatarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAvatar, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtCancelActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        if (jtfNom.getText().equals(java.util.ResourceBundle.getBundle("tourma/languages/language").getString(""))) {
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("tourma/languages/language").getString("NOM DE L'ÉQUIPE VIDE"));
        } else {
            mTeam.mName = jtfNom.getText();

            if (mTour.getParams().mEnableClans) {
                if (jcbClan.getSelectedIndex() > 0) {
                    mTeam.mClan = (Clan) Tournament.getTournament().getClans().get(jcbClan.getSelectedIndex());
                } else {
                    mTeam.mClan = (Clan) Tournament.getTournament().getClans().get(0);
                }
            }

            if (!mTour.getTeams().contains(mTeam)) {
                mTour.getTeams().add(mTeam);
            }
            this.setVisible(false);
        }

    }//GEN-LAST:event_jbtOKActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed

        final JdgCoach w = new JdgCoach(MainFrame.getMainFrame(), true, mTeam);
        w.setVisible(true);

        update();
}//GEN-LAST:event_jbtAddActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveActionPerformed
        mTour.getCoachs().remove(mTeam.mCoachs.get(jtbCoachs.getSelectedRow()));
        mTeam.mCoachs.remove(jtbCoachs.getSelectedRow());

        update();
}//GEN-LAST:event_jbtRemoveActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModifyActionPerformed

        if (jtbCoachs.getSelectedRow() >= 0) {
            final JdgCoach w = new JdgCoach(MainFrame.getMainFrame(), true, mTeam.mCoachs.get(jtbCoachs.getSelectedRow()));
            w.setVisible(true);
            update();
        }
}//GEN-LAST:event_jbtModifyActionPerformed

    private ImageIcon resize(ImageIcon image, int heigth, int width) {
        Image img = image.getImage();
        Image newimg = img.getScaledInstance(width, heigth, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(newimg);
    }

    private void jbtAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAvatarActionPerformed
        File folder;
        folder = new File(getClass().getResource("/tourma/images/flags").getFile());
        File[] listOfFiles = folder.listFiles();

        Object[] objects = new Object[listOfFiles.length + 1];

        for (int i = 0; i < listOfFiles.length; i++) {
            if (listOfFiles[i].isFile()) {
                String path = listOfFiles[i].getAbsolutePath();
                ImageIcon icon = new ImageIcon(path);
                objects[i] = resize(icon, 80, 80);
            } else if (listOfFiles[i].isDirectory()) {
                System.out.println("Directory " + listOfFiles[i].getName());
            }
        }

        ImageIcon empty = new ImageIcon();
        objects[listOfFiles.length] = empty;

        JComboBox combo = new JComboBox(objects);
        JPanel panel = new JPanel(new BorderLayout());
        JLabel l = new JLabel(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("SelectPicture"));
        panel.add(l, BorderLayout.NORTH);
        panel.add(combo, BorderLayout.CENTER);

        combo.setSelectedItem(empty);

        JOptionPane.showConfirmDialog(null, panel, null, JOptionPane.YES_OPTION);

        if (combo.getSelectedItem() == empty) {
            final JFileChooser jfc = new JFileChooser();
            final FileFilter filter1 = new ExtensionFileFilter(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("Picture"), new String[]{"PNG", "png", "JPG", "jpg", "GIF", "gif"});
            jfc.setFileFilter(filter1);
            if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                ImageIcon icon = new ImageIcon(jfc.getSelectedFile().getAbsolutePath());
                icon = resize(icon, 80, 80);
                this.mTeam.picture = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
                Graphics g = this.mTeam.picture.createGraphics();
                // paint the Icon to the BufferedImage.
                icon.paintIcon(null, g, 0, 0);
                g.dispose();
            }
        } else {
            ImageIcon icon = (ImageIcon) combo.getSelectedItem();
            this.mTeam.picture = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB);
            Graphics g = this.mTeam.picture.createGraphics();
            // paint the Icon to the BufferedImage.
            icon.paintIcon(null, g, 0, 0);
            g.dispose();
        }

        jbtAvatar.setIcon(new ImageIcon(mTeam.picture));
    }//GEN-LAST:event_jbtAvatarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtAvatar;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtModify;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtRemove;
    private javax.swing.JComboBox jcbClan;
    private javax.swing.JPanel jpnCoachButtons;
    private javax.swing.JTable jtbCoachs;
    private javax.swing.JTextField jtfNom;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
    protected void update() {

        jtfNom.setText(mTeam.mName);
        jtbCoachs.setModel(new MjtCoaches(mTeam.mCoachs));

        if (mTeam.mCoachs.size() < mTour.getParams().mTeamMatesNumber) {
            jbtOK.setEnabled(false);
        }

        if (mTeam.mCoachs.size() >= mTour.getParams().mTeamMatesNumber) {
            jbtOK.setEnabled(true);
        }

        if ((mTeam.mCoachs.size() == mTour.getParams().mTeamMatesNumber) && (!mTour.getParams().mSubstitutes)) {
            jbtAdd.setEnabled(false);
        } else {
            jbtAdd.setEnabled(true);
        }
    }
    private static final Logger LOG = Logger.getLogger(JdgTeam.class.getName());
}
