/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgCoach.java
 *
 * Created on 10 mai 2010, 19:37:53
 */
package tourma;

import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.Hashtable;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import tourma.data.Tournament;
import tourma.data.Coach;
import javax.swing.JOptionPane;
import tourma.data.Match;
import tourma.data.Round;
import tourma.data.Team;
import tourma.tableModel.mjtMatches;
import tourma.tableModel.mjtPairs;
import tourma.views.report.jdgRound;

/**
 *
 * @author Frederic Berger
 */
public class jdgTeamPairing extends javax.swing.JDialog {

    Vector<Team> _teams1;
    Vector<Team> _teams2;
    Round _round;
    Vector<Boolean> _pairsDone;

    /** Creates new form jdgCoach */
    public jdgTeamPairing(java.awt.Frame parent, boolean modal, Vector<Team> teams1, Vector<Team> teams2, Round round) {
        super(parent, modal);
        initComponents();

         GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();
        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        _teams1 = teams1;
        _teams2 = teams2;
        _round = round;

        _pairsDone = new Vector<Boolean>();
        for (int i = 0; i < _teams1.size(); i++) {
            _pairsDone.add(false);
        }

        update();

    }

    private void update() {

        mjtPairs model = new mjtPairs(_teams1, _teams2, _pairsDone);
        jtPairs.setModel(model);
        jtPairs.setDefaultRenderer(String.class, model);
        jtPairs.setDefaultRenderer(Integer.class, model);

        boolean allOK = true;
        for (int i = 0; i < _pairsDone.size(); i++) {
            allOK = allOK && _pairsDone.get(i).booleanValue();
        }
        jbtOK.setEnabled(allOK);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPairs = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jbtSeeMatches = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jbtSelect = new javax.swing.JButton();
        jbtRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jtPairs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtPairs);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jbtOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Select.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tourma/languages/language"); // NOI18N
        jbtOK.setText(bundle.getString("OK")); // NOI18N
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel2.add(jbtOK);

        jbtSeeMatches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Zoom.png"))); // NOI18N
        jbtSeeMatches.setText(bundle.getString("SeeMatchsKey")); // NOI18N
        jbtSeeMatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSeeMatchesActionPerformed(evt);
            }
        });
        jPanel2.add(jbtSeeMatches);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jbtSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Team.png"))); // NOI18N
        jbtSelect.setText(bundle.getString("SelectMatchsKeys")); // NOI18N
        jbtSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSelectActionPerformed(evt);
            }
        });
        jPanel4.add(jbtSelect);

        jbtRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Close.png"))); // NOI18N
        jbtRemove.setText(bundle.getString("CancelSelectionKey")); // NOI18N
        jbtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveActionPerformed(evt);
            }
        });
        jPanel4.add(jbtRemove);

        jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        this.setVisible(false);

    }//GEN-LAST:event_jbtOKActionPerformed

    private void jbtSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSelectActionPerformed
        if (jtPairs.getSelectedRow() >= 0) {
            jdgPairing jdg = new jdgPairing(MainFrame.getMainFrame(), true, _teams1.get(jtPairs.getSelectedRow()), _teams2.get(jtPairs.getSelectedRow()), _round);
            jdg.setVisible(true);
            _pairsDone.setElementAt(true, jtPairs.getSelectedRow());
        }
        update();
}//GEN-LAST:event_jbtSelectActionPerformed

    private void jbtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveActionPerformed

        if (jtPairs.getSelectedRow() >= 0) {
            _pairsDone.setElementAt(false, jtPairs.getSelectedRow());

            Team t1 = _teams1.get(jtPairs.getSelectedRow());
            int i = 0;
            while (i < _round.getMatchs().size()) {
                if ((_round.getMatchs().get(i)._coach1._teamMates == t1) ||
                        (_round.getMatchs().get(i)._coach2._teamMates == t1)) {
                    _round.getMatchs().remove(i);
                    i = 0;
                } else {
                    i++;
                }
            }
        }
        update();
}//GEN-LAST:event_jbtRemoveActionPerformed

    private void jbtSeeMatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSeeMatchesActionPerformed

        int nb=1;
        for (int i=0; i<Tournament.getTournament().getRounds().size(); i++)
        {
            if (Tournament.getTournament().getRounds().get(i).getHeure().before(_round.getHeure()))
            {
                nb++;
            }
        }
        jdgRound jdg = new jdgRound(MainFrame.getMainFrame(), true, _teams1,_teams2,nb, Tournament.getTournament());
        jdg.setVisible(true);
    }//GEN-LAST:event_jbtSeeMatchesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtRemove;
    private javax.swing.JButton jbtSeeMatches;
    private javax.swing.JButton jbtSelect;
    private javax.swing.JTable jtPairs;
    // End of variables declaration//GEN-END:variables
}
