/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JdgCoach.java
 *
 * Created on 10 mai 2010, 19:37:53
 */
package tourma;

import java.awt.BorderLayout;
import java.awt.DisplayMode;
import java.awt.Graphics;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileFilter;
import tourma.data.Team;
import tourma.data.Tournament;
import tourma.tableModel.MjtCoaches;
import tourma.utility.ExtensionFileFilter;

/**
 *
 * @author Frederic Berger
 */
public final class JdgTeam extends javax.swing.JDialog {

    private boolean mTeamTournament;
    private Team mTeam;
    private Tournament mTour;

    /**
     *
     * @param parent
     * @param modal
     */
    public JdgTeam(final java.awt.Frame parent, final boolean modal) {
        super(parent, modal);
        initComponents();

        mTour = Tournament.getTournament();
        mTeam = new Team();

        final GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        final GraphicsDevice gs = ge.getDefaultScreenDevice();
        final DisplayMode dmode = gs.getDisplayMode();

        final int screenWidth = dmode.getWidth();
        final int screenHeight = dmode.getHeight();
        this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);

        if (mTeam.getPicture() == null) {
            try {
                mTeam.setPicture(ImageIO.read(getClass().getResource("/tourma/images/flags/Country France.png")));
            } catch (IOException ex) {
                Logger.getLogger(JdgCoach.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jbtAvatar.setIcon(resize(new ImageIcon(mTeam.getPicture()), 80, 80));

        final DefaultComboBoxModel clanListModel = new DefaultComboBoxModel();
        for (int i = 0; i < Tournament.getTournament().getClansCount(); i++) {
            clanListModel.addElement(Tournament.getTournament().getClan(i).getName());
        }
        jcbClan.setModel(clanListModel);

        if ((Tournament.getTournament().getParams().isEnableClans()) && (Tournament.getTournament().getClansCount() > 1)) {
            jcbClan.setEnabled(true);
            jLabel2.setEnabled(true);
        } else {
            jcbClan.setEnabled(false);
            jLabel2.setEnabled(false);
        }

        update();
    }

    /**
     *
     * @param parent
     * @param modal
     * @param team
     */
    public JdgTeam(final java.awt.Frame parent, final boolean modal, final Team team) {
        super(parent, modal);
        initComponents();

        mTour = Tournament.getTournament();
        mTeam = team;

        jtbCoachs.setModel(new MjtCoaches(mTeam));

        final GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        final GraphicsDevice gs = ge.getDefaultScreenDevice();
        final DisplayMode dmode = gs.getDisplayMode();

        final int screenWidth = dmode.getWidth();
        final int screenHeight = dmode.getHeight();
        this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);

        if (mTeam.getPicture() == null) {
            mTeam.setPicture(new BufferedImage(96, 96, BufferedImage.TYPE_4BYTE_ABGR));
        }

        final DefaultComboBoxModel clanListModel = new DefaultComboBoxModel();
        for (int i = 0; i < Tournament.getTournament().getClansCount(); i++) {
            clanListModel.addElement(Tournament.getTournament().getClan(i).getName());
        }
        jcbClan.setModel(clanListModel);

        if ((Tournament.getTournament().getParams().isEnableClans()) && (Tournament.getTournament().getClansCount() > 1)) {
            jcbClan.setEnabled(true);
            if (team.getClan() != null) {
                jcbClan.setSelectedItem(team.getClan().getName());
            }
        }

        jbtAvatar.setIcon(resize(new ImageIcon(mTeam.getPicture()), 80, 80));
        update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcbClan = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jbtCancel = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jpnCoachButtons = new javax.swing.JPanel();
        jbtAdd = new javax.swing.JButton();
        jbtRemove = new javax.swing.JButton();
        jbtModify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCoachs = new javax.swing.JTable();
        jbtAvatar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("tourma/languages/language"); // NOI18N
        jLabel1.setText(bundle.getString("TeamNameKey")); // NOI18N
        jPanel1.add(jLabel1);
        jPanel1.add(jtfNom);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText(bundle.getString("ClanNameKey")); // NOI18N
        jPanel1.add(jLabel2);

        jPanel1.add(jcbClan);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jbtOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Select.png"))); // NOI18N
        jbtOK.setText(bundle.getString("OK")); // NOI18N
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel2.add(jbtOK);

        jbtCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Halt.png"))); // NOI18N
        jbtCancel.setText(bundle.getString("Cancel")); // NOI18N
        jbtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jbtCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Coachs"));
        jPanel7.setPreferredSize(new java.awt.Dimension(450, 240));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jbtAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Add.png"))); // NOI18N
        jbtAdd.setText(bundle.getString("Add")); // NOI18N
        jbtAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddActionPerformed(evt);
            }
        });
        jpnCoachButtons.add(jbtAdd);

        jbtRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Close.png"))); // NOI18N
        jbtRemove.setText(bundle.getString("Remove")); // NOI18N
        jbtRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveActionPerformed(evt);
            }
        });
        jpnCoachButtons.add(jbtRemove);

        jbtModify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tourma/images/Swap.png"))); // NOI18N
        jbtModify.setText(bundle.getString("Modify")); // NOI18N
        jbtModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModifyActionPerformed(evt);
            }
        });
        jpnCoachButtons.add(jbtModify);

        jPanel7.add(jpnCoachButtons, java.awt.BorderLayout.PAGE_START);

        jtbCoachs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbCoachs.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jtbCoachs);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        jbtAvatar.setMnemonic('A');
        jbtAvatar.setPreferredSize(new java.awt.Dimension(80, 80));
        jbtAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAvatarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtAvatar, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtCancelActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed

        if (jtfNom.getText().equals(java.util.ResourceBundle.getBundle("tourma/languages/language").getString(""))) {
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("tourma/languages/language").getString("NOM DE L'ÉQUIPE VIDE"));
        } else {
            mTeam.setName(jtfNom.getText());

            if (mTour.getParams().isEnableClans()) {
                if (jcbClan.getSelectedIndex() > 0) {
                    mTeam.setClan(Tournament.getTournament().getClan(jcbClan.getSelectedIndex()));
                } else {
                    mTeam.setClan(Tournament.getTournament().getClan(0));
                }
            }

            if (!mTour.containsTeam(mTeam)) {
                mTour.addTeam(mTeam);
            }
            this.setVisible(false);
        }

    }//GEN-LAST:event_jbtOKActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddActionPerformed

        final JdgCoach w = new JdgCoach(MainFrame.getMainFrame(), true, mTeam);
        w.setVisible(true);

        update();
}//GEN-LAST:event_jbtAddActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveActionPerformed
        mTour.removeCoach(mTeam.getCoach(jtbCoachs.getSelectedRow()));
        mTeam.removeCoach(jtbCoachs.getSelectedRow());

        update();
}//GEN-LAST:event_jbtRemoveActionPerformed
    @SuppressWarnings({"PMD.UnusedFormalParameter", "PMD.MethodArgumentCouldBeFinal"})
    private void jbtModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModifyActionPerformed

        if (jtbCoachs.getSelectedRow() >= 0) {
            final JdgCoach w = new JdgCoach(MainFrame.getMainFrame(), true, mTeam.getCoach(jtbCoachs.getSelectedRow()));
            w.setVisible(true);
            update();
        }
}//GEN-LAST:event_jbtModifyActionPerformed

    private ImageIcon resize(ImageIcon image, int heigth, int width) {
        Image img = image.getImage();
        Image newimg = img.getScaledInstance(width, heigth, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(newimg);
    }

    public List<ImageIcon> getImagesResources(final String path) throws IOException {
        final ClassLoader loader = Thread.currentThread().getContextClassLoader();
        ArrayList<ImageIcon> list = new ArrayList<>();
        final File jarFile = new File(getClass().getProtectionDomain().getCodeSource().getLocation().getPath());
        if (jarFile == null) {
            System.out.println("Jarfile is null: " + getClass().getProtectionDomain().getCodeSource().getLocation().getPath());
        } else {
            System.out.println("Open JAR File: " + getClass().getProtectionDomain().getCodeSource().getLocation().getPath());
        }

        if (jarFile.isFile()) {  // Run with JAR file
            final JarFile jar = new JarFile(jarFile);
            final Enumeration<JarEntry> entries = jar.entries(); //gives ALL entries in jar
            while (entries.hasMoreElements()) {
                final String name = entries.nextElement().getName();
                //System.out.println("Open JAR File: "+name);
                String pathToTest;
                if (path.startsWith("/")) {
                    pathToTest = path.subSequence(1, path.length()).toString();
                } else {
                    pathToTest = path;
                }
                // System.out.println("Tests "+name+" starts with "+pathToTest);
                if (name.startsWith(pathToTest + "/")) { //filter according to the path
                    BufferedImage bi=ImageIO.read(getClass().getResource("/tourma/images/flags/Country France.png"));
                    bi=ImageIO.read(getClass().getResource("/"+name));
                    if (bi==null)
                    {
                        System.out.println("/"+name+" returns a null image");
                    }
                    else
                    {
                        ImageIcon ii=new ImageIcon(bi);
                        list.add(ii);
                    }
                }
            }
            jar.close();
        } else { // Run with IDE
            try {
                final URL url = getClass().getResource(path).toURI().toURL();
                if (url != null) {
                    try {
                        final File apps = new File(url.toURI());
                        for (File app : apps.listFiles()) {
                            ImageIcon icon = new ImageIcon(app.getAbsolutePath());
                            list.add(icon);
                        }
                    } catch (URISyntaxException ex) {
                        // never happens
                    }
                }
            } catch (URISyntaxException ex) {
                LOG.log(Level.WARNING, ex.getLocalizedMessage());
            }
        }
        return list;
    }

    private void jbtAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAvatarActionPerformed

        try {
            List<ImageIcon> listOfFiles = getImagesResources("/tourma/images/flags");

            Object[] objects = new Object[listOfFiles.size() + 1];
            for (int i = 0; i < listOfFiles.size(); i++) {
                if (listOfFiles.get(i) != null) {
                    objects[i] = resize(listOfFiles.get(i), 80, 80);
                }
            }
            ImageIcon empty = new ImageIcon();
            objects[listOfFiles.size()] = empty;

            JComboBox<Object> combo = new JComboBox<>(objects);
            JPanel panel = new JPanel(new BorderLayout());
            JLabel l = new JLabel(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("SelectPicture"));
            panel.add(l, BorderLayout.NORTH);
            panel.add(combo, BorderLayout.CENTER);

            combo.setSelectedItem(empty);

            JOptionPane.showConfirmDialog(null, panel, null, JOptionPane.YES_OPTION);

            if (combo.getSelectedItem() == empty) {
                final JFileChooser jfc = new JFileChooser();
                final FileFilter filter1 = new ExtensionFileFilter(java.util.ResourceBundle.getBundle("tourma/languages/language").getString("Picture"), new String[]{"PNG", "png", "JPG", "jpg", "GIF", "gif"});
                jfc.setFileFilter(filter1);
                if (jfc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
                    ImageIcon icon = new ImageIcon(jfc.getSelectedFile().getAbsolutePath());
                    icon = resize(icon, 80, 80);
                    this.mTeam.setPicture(new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB));
                    Graphics g = this.mTeam.getPicture().createGraphics();
                    // paint the Icon to the BufferedImage.
                    icon.paintIcon(null, g, 0, 0);
                    g.dispose();
                }
            } else {
                ImageIcon icon = (ImageIcon) combo.getSelectedItem();
                this.mTeam.setPicture(new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_ARGB));
                Graphics g = this.mTeam.getPicture().createGraphics();
                // paint the Icon to the BufferedImage.
                icon.paintIcon(null, g, 0, 0);
                g.dispose();
            }

            jbtAvatar.setIcon(new ImageIcon(mTeam.getPicture()));
        } catch (IOException use) {
            LOG.log(Level.WARNING, use.getLocalizedMessage());
        }
    }//GEN-LAST:event_jbtAvatarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAdd;
    private javax.swing.JButton jbtAvatar;
    private javax.swing.JButton jbtCancel;
    private javax.swing.JButton jbtModify;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtRemove;
    private javax.swing.JComboBox jcbClan;
    private javax.swing.JPanel jpnCoachButtons;
    private javax.swing.JTable jtbCoachs;
    private javax.swing.JTextField jtfNom;
    // End of variables declaration//GEN-END:variables

    /**
     * Update hmi
     */
    private void update() {

        jtfNom.setText(mTeam.getName());
        jtbCoachs.setModel(new MjtCoaches(mTeam));

        if (mTeam.getCoachCount() < mTour.getParams().getTeamMatesNumber()) {
            jbtOK.setEnabled(false);
        }

        if (mTeam.getCoachCount() >= mTour.getParams().getTeamMatesNumber()) {
            jbtOK.setEnabled(true);
        }

        if ((mTeam.getCoachCount() == mTour.getParams().getTeamMatesNumber()) && (!mTour.getParams().isSubstitutes())) {
            jbtAdd.setEnabled(false);
        } else {
            jbtAdd.setEnabled(true);
        }
    }
    private static final Logger LOG = Logger.getLogger(JdgTeam.class
            .getName());

    private void writeObject(java.io.ObjectOutputStream stream) throws java.io.IOException {
        throw new java.io.NotSerializableException(getClass().getName());
    }

    private void readObject(java.io.ObjectInputStream stream) throws java.io.IOException, ClassNotFoundException {
        throw new java.io.NotSerializableException(getClass().getName());
    }

    private ImageIcon ImageIcon(URL resource) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
