/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgAbout.java
 *
 * Created on 27 mai 2009, 11:08:24
 */

package tourma.views.system;

import tourma.*;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author root.106572700130
 */
public class jdgOnlineHelp extends javax.swing.JDialog {

    /** Creates new form jdgAbout */
    public jdgOnlineHelp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        this.setSize(580, 350);

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

         jepCreateTour.setContentType("html");
         jepAddCoach.setContentType("html");
         jepEnterMatchs.setContentType("html");
         jepEraseRound.setContentType("html");
         jepGenerateNextRound.setContentType("html");
         jepLoadSave.setContentType("html");
         jepPrint.setContentType("html");
         jepUpload.setContentType("html");
         jepNafExport.setContentType("html");
         jepVoirClassements.setContentType("html");
         try
         {
            jepCreateTour.setPage(getClass().getResource("/tourma/views/system/help/createtour.html").toString());
            jepAddCoach.setPage(getClass().getResource("/tourma/views/system/help/addcoach.html").toString());
            jepEnterMatchs.setPage(getClass().getResource("/tourma/views/system/help/entermatches.html").toString());
            jepEraseRound.setPage(getClass().getResource("/tourma/views/system/help/eraseround.html").toString());
            jepGenerateNextRound.setPage(getClass().getResource("/tourma/views/system/help/generateround.html").toString());
            jepLoadSave.setPage(getClass().getResource("/tourma/views/system/help/loadsave.html").toString());
            jepPrint.setPage(getClass().getResource("/tourma/views/system/help/print.html").toString());
            jepUpload.setPage(getClass().getResource("/tourma/views/system/help/upload.html").toString());
            jepNafExport.setPage(getClass().getResource("/tourma/views/system/help/nafexport.html").toString());
            jepVoirClassements.setPage(getClass().getResource("/tourma/views/system/help/viewrank.html").toString());
         }
         catch (IOException e)
         {
               JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
         }
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepCreateTour = new javax.swing.JEditorPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jepAddCoach = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jepGenerateNextRound = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jepEnterMatchs = new javax.swing.JEditorPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jepLoadSave = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jepUpload = new javax.swing.JEditorPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jepPrint = new javax.swing.JEditorPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jepEraseRound = new javax.swing.JEditorPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jepVoirClassements = new javax.swing.JEditorPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jepNafExport = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("A propos de");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jepCreateTour.setContentType("text/html");
        jepCreateTour.setEditable(false);
        jScrollPane1.setViewportView(jepCreateTour);

        jTabbedPane1.addTab("Créer un tournoi", jScrollPane1);

        jScrollPane2.setViewportView(jepAddCoach);

        jTabbedPane1.addTab("Ajouter des coachs", jScrollPane2);

        jScrollPane3.setViewportView(jepGenerateNextRound);

        jTabbedPane1.addTab("Générer une ronde", jScrollPane3);

        jScrollPane4.setViewportView(jepEnterMatchs);

        jTabbedPane1.addTab("Saisir les matchs", jScrollPane4);

        jScrollPane5.setViewportView(jepLoadSave);

        jTabbedPane1.addTab("Enregistrer/Charger tournoi", jScrollPane5);

        jScrollPane6.setViewportView(jepUpload);

        jTabbedPane1.addTab("Uploader sur le Web", jScrollPane6);

        jScrollPane7.setViewportView(jepPrint);

        jTabbedPane1.addTab("Imprimer un classement", jScrollPane7);

        jScrollPane8.setViewportView(jepEraseRound);

        jTabbedPane1.addTab("Effacer une ronde", jScrollPane8);

        jScrollPane9.setViewportView(jepVoirClassements);

        jTabbedPane1.addTab("Voir les classements", jScrollPane9);

        jScrollPane10.setViewportView(jepNafExport);

        jTabbedPane1.addTab("Exporter pour la NAF", jScrollPane10);

        jPanel3.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Un peu d'aide en ligne");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JEditorPane jepAddCoach;
    private javax.swing.JEditorPane jepCreateTour;
    private javax.swing.JEditorPane jepEnterMatchs;
    private javax.swing.JEditorPane jepEraseRound;
    private javax.swing.JEditorPane jepGenerateNextRound;
    private javax.swing.JEditorPane jepLoadSave;
    private javax.swing.JEditorPane jepNafExport;
    private javax.swing.JEditorPane jepPrint;
    private javax.swing.JEditorPane jepUpload;
    private javax.swing.JEditorPane jepVoirClassements;
    // End of variables declaration//GEN-END:variables

}
