/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgAbout.java
 *
 * Created on 27 mai 2009, 11:08:24
 */

package tourma.views.system;

import tourma.*;
import java.awt.DisplayMode;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.Vector;
import javax.swing.ListSelectionModel;



/**
 *
 * @author root.106572700130
 */
public class jdgRevisions extends javax.swing.JDialog {

    /** Creates new form jdgAbout */
    public jdgRevisions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gs = ge.getDefaultScreenDevice();
        DisplayMode dmode = gs.getDisplayMode();

        this.setSize(580, 350);

        if (dmode != null) {
            int screenWidth = dmode.getWidth();
            int screenHeight = dmode.getHeight();
            this.setLocation((screenWidth - this.getWidth()) / 2, (screenHeight - this.getHeight()) / 2);
        }

        Vector versions=new Vector();
        Vector descriptions=new Vector();

        int n=1;
        String tmpV=Version.getSingleton().getProperty(Integer.toString(n)+"-V");
        String tmpD=Version.getSingleton().getProperty(Integer.toString(n)+"-D");

        while (tmpV!=null)
        {
            versions.add(tmpV);
            descriptions.add(tmpD);
            n++;
            tmpV=Version.getSingleton().getProperty(Integer.toString(n)+"-V");
            tmpD=Version.getSingleton().getProperty(Integer.toString(n)+"-D");
        }

    mtRevisions model=new mtRevisions(versions, descriptions);
    jxtVersions.setModel(model);
    jxtVersions.setDefaultRenderer(String.class, model);
    jxtVersions.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    pack();
    repaint();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jxtVersions = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Révisions");
        setMinimumSize(new java.awt.Dimension(640, 480));

        jPanel1.setMinimumSize(new java.awt.Dimension(320, 33));
        jPanel1.setPreferredSize(new java.awt.Dimension(320, 33));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jxtVersions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jxtVersions);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jxtVersions;
    // End of variables declaration//GEN-END:variables

}
