/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jdgRoundReport.java
 *
 * Created on 28 juin 2010, 10:52:47
 */
package tourma.views.report;

import tourma.*;
import tourma.data.Round;
import tourma.data.Tournament;
import tourma.data.Match;
import freemarker.template.Configuration;
import freemarker.template.DefaultObjectWrapper;
import freemarker.template.Template;
import freemarker.template.TemplateException;

import java.awt.Dimension;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import tourma.data.Team;
import tourma.tableModel.mjtMatchTeams;

/**
 *
 * @author Frederic Berger
 */
public class jdgRound extends javax.swing.JDialog {

    Round _round;
    int _roundNumber;
    Tournament _tour;
    boolean _result;
    boolean _team = false;
    Vector<Team> _teams1;
    Vector<Team> _teams2;
    File _filename = null;

    /** Creates new form jdgRoundReport */
    public jdgRound(java.awt.Frame parent, boolean modal, Round round, int roundNumber, Tournament tour, boolean result, boolean team) {
        super(parent, modal);
        initComponents();
        _round = round;
        _roundNumber = roundNumber;
        _tour = tour;
        _result = result;
        _team = team;

        this.setTitle(tour.getParams()._tournament_name + " - Ronde " + roundNumber);
        try {
            jepHTML.setContentType("html");
            File f;

            if (_team) {
                _filename = CreateTeamReport();
            } else {
                _filename = CreateReport();
            }
            jepHTML.setPage(_filename.toURI().toURL());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(parent, e.getLocalizedMessage());
        }
        this.setPreferredSize(new Dimension(800, 600));
        pack();
    }

    public jdgRound(java.awt.Frame parent, boolean modal, Vector<Team> teams1, Vector<Team> teams2, int roundNumber, Tournament tour) {
        super(parent, modal);
        initComponents();

        _teams1 = teams1;
        _teams2 = teams2;
        _roundNumber = roundNumber;
        _tour = tour;

        this.setTitle(tour.getParams()._tournament_name + " - Ronde " + roundNumber);
        try {
            jepHTML.setContentType("html");
            File f;
            f = CreateEmptyTeamReport();

            jepHTML.setPage(f.toURI().toURL());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(parent, e.getLocalizedMessage());
        }
        this.setPreferredSize(new Dimension(800, 600));
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtOK = new javax.swing.JButton();
        jbtPrint = new javax.swing.JButton();
        jbtExport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepHTML = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtOK.setText("OK");
        jbtOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtOKActionPerformed(evt);
            }
        });
        jPanel1.add(jbtOK);

        jbtPrint.setText("Imprimer");
        jbtPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrintActionPerformed(evt);
            }
        });
        jPanel1.add(jbtPrint);

        jbtExport.setText("Export HTML");
        jbtExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExportActionPerformed(evt);
            }
        });
        jPanel1.add(jbtExport);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(jepHTML);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtOKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbtOKActionPerformed

    private void jbtPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrintActionPerformed
        try {
            jepHTML.print();

        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(MainFrame.getMainFrame(), e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jbtPrintActionPerformed

    private void jbtExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExportActionPerformed
        JFileChooser jfc = new JFileChooser();
        if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File export = jfc.getSelectedFile();

            try {
                FileReader in = new FileReader(_filename);
                FileWriter out = new FileWriter(export);
                int c;

                while ((c = in.read()) != -1) {
                    out.write(c);
                }

                in.close();
                out.close();
            } catch (FileNotFoundException fnf) {
                JOptionPane.showMessageDialog(this, fnf.getLocalizedMessage());
            } catch (IOException ioe) {
                JOptionPane.showMessageDialog(this, ioe.getLocalizedMessage());
            }
        }
    }//GEN-LAST:event_jbtExportActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtExport;
    private javax.swing.JButton jbtOK;
    private javax.swing.JButton jbtPrint;
    private javax.swing.JEditorPane jepHTML;
    // End of variables declaration//GEN-END:variables

    private File CreateReport() {
        File address = null;

        try {
            Configuration cfg = new Configuration();
            URI uri = getClass().getResource("/tourma/views/report").toURI();
            if (uri.toString().contains(".jar!")) {
                /* JOptionPane.showMessageDialog(this,"Dans un jar: "+uri.toString());
                String tmp=uri.toString();
                tmp=tmp.substring(10, tmp.indexOf(".jar!")-4);
                JOptionPane.showMessageDialog(this,tmp);
                //tmp=tmp+"";
                cfg.setDirectoryForTemplateLoading(new File(tmp));*/
                cfg.setClassForTemplateLoading(getClass(), "");
            } else {
                cfg.setDirectoryForTemplateLoading(new File(uri));
            }
            cfg.setObjectWrapper(new DefaultObjectWrapper());
            Template temp = cfg.getTemplate("round.html");

            Map root = new HashMap();
            root.put("nom", _tour.getParams()._tournament_name + " - Ronde " + _roundNumber);
            root.put("tables", _round.getMatchs().size());

            Vector<Match> matches = _round.getMatchs();
            Vector parMatches = new Vector();
            if (_result) {
                root.put("result", 1);
            } else {
                root.put("result", 0);
            }
            for (int i = 0; i < matches.size(); i++) {
                Match match = matches.get(i);

                HashMap m = new HashMap();
                m.put("numero", i + 1);
                m.put("coach1", match._coach1._name);
                if (_result) {
                    m.put("score1", match._td1);
                    m.put("score2", match._td2);
                    m.put("sorties1", match._sor1);
                    m.put("sorties2", match._sor2);
                    m.put("foul1", match._foul1);
                    m.put("foul2", match._foul2);
                } else {
                    m.put("score1", "&nbsp;");
                    m.put("score2", "&nbsp;");
                    m.put("sorties1", "&nbsp;");
                    m.put("sorties2", "&nbsp;");
                    m.put("foul1", "&nbsp;");
                    m.put("foul2", "&nbsp;");
                }
                m.put("coach2", match._coach2._name);
                parMatches.add(m);
            }

            root.put("matches", parMatches);

            SimpleDateFormat format = new SimpleDateFormat("EEEEEEE dd MMMMMMMMMMM yyyy");
            SimpleDateFormat formatShort = new SimpleDateFormat("dd/MM/yyyy");
            root.put("dateGeneration", formatShort.format(new Date()));
            address = File.createTempFile("result" + format.format(new Date()), ".tmp");
            address.deleteOnExit();
            Writer out = new FileWriter(address);
            temp.process(root, out);
            out.flush();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (TemplateException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (URISyntaxException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        }
        return address;
    }

    private File CreateTeamReport() {
        File address = null;

        try {
            Configuration cfg = new Configuration();
            URI uri = getClass().getResource("/tourma/views/report").toURI();
            if (uri.toString().contains(".jar!")) {
                /* JOptionPane.showMessageDialog(this,"Dans un jar: "+uri.toString());
                String tmp=uri.toString();
                tmp=tmp.substring(10, tmp.indexOf(".jar!")-4);
                JOptionPane.showMessageDialog(this,tmp);
                //tmp=tmp+"";
                cfg.setDirectoryForTemplateLoading(new File(tmp));*/
                cfg.setClassForTemplateLoading(getClass(), "");
            } else {
                cfg.setDirectoryForTemplateLoading(new File(uri));
            }
            cfg.setObjectWrapper(new DefaultObjectWrapper());
            Template temp = cfg.getTemplate("team_round.html");

            Map root = new HashMap();
            root.put("nom", _tour.getParams()._tournament_name + " - Ronde " + _roundNumber);
            root.put("tables", _round.getMatchs().size());

            Vector<Team> teams = new Vector<Team>();
            for (int i = 0; i < _round.getMatchs().size(); i++) {
                Match m = _round.getMatchs().get(i);
                Team team1 = m._coach1._teamMates;
                Team team2 = m._coach2._teamMates;
                if (!teams.contains(team1)) {
                    teams.add(team1);
                }
                if (!teams.contains(team2)) {
                    teams.add(team2);
                }
            }
            mjtMatchTeams model = new mjtMatchTeams(teams, _round);
            Vector parMatches = new Vector();
            for (int i = 0; i < model.getRowCount(); i++) {

                HashMap m = new HashMap();
                m.put("numero", model.getValueAt(i, 0));
                m.put("clan1", model.getValueAt(i, 1));
                if (_result) {
                    m.put("v1", model.getValueAt(i, 2));
                    m.put("n", model.getValueAt(i, 3));
                    m.put("v2", model.getValueAt(i, 4));
                } else {
                    m.put("v1", "&nbsp;");
                    m.put("n", "&nbsp;");
                    m.put("v2", "&nbsp;");
                }
                m.put("clan2", model.getValueAt(i, 5));
                parMatches.add(m);
            }

            root.put("matches", parMatches);

            SimpleDateFormat format = new SimpleDateFormat("EEEEEEE dd MMMMMMMMMMM yyyy");
            SimpleDateFormat formatShort = new SimpleDateFormat("dd/MM/yyyy");
            root.put("dateGeneration", formatShort.format(new Date()));
            address = File.createTempFile("result" + format.format(new Date()), ".tmp");
            address.deleteOnExit();
            Writer out = new FileWriter(address);
            temp.process(root, out);
            out.flush();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (TemplateException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (URISyntaxException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        }
        return address;
    }

    private File CreateEmptyTeamReport() {
        File address = null;

        try {
            Configuration cfg = new Configuration();
            URI uri = getClass().getResource("/tourma/views/report").toURI();
            if (uri.toString().contains(".jar!")) {
                /* JOptionPane.showMessageDialog(this,"Dans un jar: "+uri.toString());
                String tmp=uri.toString();
                tmp=tmp.substring(10, tmp.indexOf(".jar!")-4);
                JOptionPane.showMessageDialog(this,tmp);
                //tmp=tmp+"";
                cfg.setDirectoryForTemplateLoading(new File(tmp));*/
                cfg.setClassForTemplateLoading(getClass(), "");
            } else {
                cfg.setDirectoryForTemplateLoading(new File(uri));
            }
            cfg.setObjectWrapper(new DefaultObjectWrapper());
            Template temp = cfg.getTemplate("team_round.html");

            Map root = new HashMap();
            root.put("nom", _tour.getParams()._tournament_name + " - Ronde " + _roundNumber);
            root.put("tables", _tour.getTeams().size() / 2);
            root.put("result", 0);

            Vector parMatches = new Vector();
            for (int i = 0; i < _teams1.size(); i++) {
                HashMap m = new HashMap();
                m.put("numero", i + 1);
                m.put("clan1", _teams1.get(i)._name);
                m.put("v1", "&nbsp;");
                m.put("n", "&nbsp;");
                m.put("v2", "&nbsp;");

                m.put("clan2", _teams2.get(i)._name);
                parMatches.add(m);
            }

            root.put("matches", parMatches);

            SimpleDateFormat format = new SimpleDateFormat("EEEEEEE dd MMMMMMMMMMM yyyy");
            SimpleDateFormat formatShort = new SimpleDateFormat("dd/MM/yyyy");
            root.put("dateGeneration", formatShort.format(new Date()));
            address = File.createTempFile("result" + format.format(new Date()), ".tmp");
            address.deleteOnExit();
            Writer out = new FileWriter(address);
            temp.process(root, out);
            out.flush();

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (TemplateException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        } catch (URISyntaxException e) {
            JOptionPane.showMessageDialog(this, e.getLocalizedMessage());
        }
        return address;
    }
}
